### ISSUE TITLE
Writable book doesn't work

### ISSUE THREAD

**Issue by joserobjr** [PowerNukkit/PowerNukkit#10]
We can't edit the books, all changes are lost

https://github.com/NukkitX/Nukkit/issues/797

**Comment by joserobjr** [comment]
https://github.com/majovec/CoreX/blob/e573bc846b80c89c308bc15665714d087a45ab43/src/main/java/cn/nukkit/network/protocol/BookEditPacket.java

https://github.com/DarkSystem-PE/DarkSystem/blob/9bacdd9aae650cdec435ac3e54ec50464ee8b9f2/src/pocketmine/network/protocol/v120/BookEditPacket.php

**Comment by Hancho1577** [comment]
Implemented in #1310

**Comment by MrRazamataz** [comment]
You can write in a book and quill and its saves but you can only sign them in Creative mode, not survival.

**Comment by LoboMetalurgico** [comment]
Fixed in #1194
