### ISSUE TITLE
Dark Oak Leaves

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1000]
# 🐞 I found a bug
 You can't place Dark Oak Leaves when it's breaking with shears from Dark Oak trees.
And you can't drop this item.

### ▶ Steps to Reproduce

1. Take a Shear and looking for Dark Oak Tree
2. Break the leaves with shears 
3. Now, try to drop them or try to place this leaves
4. Doenst work
5. Tested without Plugins
6. It's very rare but many times, dark Oak trees drops a Acadia Log Block

### 📋 Debug information

* PowerNukkit version: (git-1d52f45)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by GoodLucky777** [comment]
related to #976
