### ISSUE TITLE
Command blocks

### ISSUE THREAD

**Issue by MrCrazyMan109** [PowerNukkit/PowerNukkit#1001]
# ❇ Feature Request

It would be pretty nice if command blocks could be implemented into PowerNukkit. It makes life a lot easier :) 
(well, at least for me.)

Thank you!

https://debugpaste.powernukkit.org/pastes/PN43bd2260/

**Comment by Superzock3003** [comment]
Hey @MrCrazyMan109! There is already a plugin for commandblocks, if you really need them: https://github.com/wode490390/VanillaCommandBlock/releases/tag/1.0.0

**Comment by GoodLucky777** [comment]
Duplicated with #122

**Comment by LoboMetalurgico** [comment]
Closed. Reason: Duplicate of issue #122
