### ISSUE TITLE
Outdated Version of Minecraft

### ISSUE THREAD

**Issue by GabeCoder** [PowerNukkit/PowerNukkit#1002]
# 🔌 Plugin compatibility issue
Although this doesn’t have to do with plugin compatibilities, the version of Minecraft that this host runs is: 1.16.201, which is the outdated version. The latest is 1.16.210, which Mojang added to fix some issues and add a sneak peak to the Caves and Cliffs update.

### 📸 Screenshots / Videos
Unavailable

### ▶ Steps to Reproduce

1. Run command 'java -jar powernukkit-1.3.2.0-PN-ALPHA.3-CUSTOM-shaded.jar'
2. On Minecraft Bedrock Edition, click on 'Play > Servers'
3. Put 'SERVER IP' at 'Server Address'
4. Join server and see error (ONLY ON 1.16.210)

### ✔ Expected Behavior

I expected to join the server as if I was a casual player.

### ❌ Actual Behavior

I got disconnected from the server because it was outdated.

### 📋 Debug information
I have no idea what debugging is, but I know what version I am running.

* PowerNukkit version: ALPHA 3
* Debug link: ✍
* Timings link (if relevant): ✍ 

### 💢 Crash Dump, Stack Trace and Other Files

The server doesn’t crash, however, it won’t let you join if you’re running 1.16.210.

### 💬 Anything else we should know?

Does ```git submodule update —init``` actually update the contents of the PowerNukkit folder so the server is up to date, or is there another way? How do you update your server?

**Comment by LoboMetalurgico** [comment]
Please, use the 1.4.0.0 version for this minecraft version.

Here is the https://github.com/PowerNukkit/PowerNukkit/actions/runs/666468784 link.

This version is unstable, so I recommend that you back up your data before migrating. After migrating to any version of 1.4.x it is impossible to return to version 1.3.x;

**Comment by GabeCoder** [comment]
> Please, use the 1.4.0.0 version for this minecraft version.
> 
> Here is the https://github.com/PowerNukkit/PowerNukkit/actions/runs/666468784 link.
> 
> This version is unstable, so I recommend that you back up your data before migrating. After migrating to any version of 1.4.x it is impossible to return to version 1.3.x;

This is understandable. Thank you for letting me know.

**Comment by GabeCoder** [comment]
Update: Minecraft 1.16.210 is now compatible with Linux, so I think this means that the server host can be updated too.
The bleeding one didn’t work because it probably had Minecraft compatibility issues.

**Comment by Gabriel8579** [comment]
You can run the server in any device that can run Java
