### ISSUE TITLE
Food Bug

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1018]
# 🐞 I found a bug
 You don't consume any food if you right-click for a moment to eat. Your life and hunger will be replenished

### ▶ Steps to Reproduce

1. Look for food
2. hold the button to eat only briefly
3. Now you can see, you're Hunger and life was restored without lose consumable Items

### 📋 Debug information

* PowerNukkit version: (git-b7f4ffa)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by Jl1mbo** [comment]
#961

**Comment by MonoAdrian23** [comment]
Ah sorry, thank you
