### ISSUE TITLE
Outdated Version of Minecraft (New)

### ISSUE THREAD

**Issue by GabeCoder** [PowerNukkit/PowerNukkit#1019]
Since Minecraft Bedrock Edition finally received a compatible update for Linux, I suppose that it’s time that PowerNukkit upgrades to 1.16.210.
The bleeding 1.4.0.0 release hasn’t setup correctly, probably because of the compatibility issue.
I have mentioned the same exact problem in issue #1002 before the stable release happened.
Please make sure to update your PowerNukkit host, since many Bedrock Edition players won’t be able to join if the server is outdated.
The latest stable release is ALPHA 3.
I can’t run the bleeding release, as said.

**Comment by joserobjr** [comment]
Hi! Checkout the latest stable release, it supports 1.16.221:
https://powernukkit.org/releases
