### ISSUE TITLE
In Creative Mode, no stone slabs are available.

### ISSUE THREAD

**Issue by joserobjr** [PowerNukkit/PowerNukkit#1027]
# 🐞 I found a bug

In Creative Mode, no stone slabs are available.
Sandstone, Red Sandstone, Stone, smooth Stoneslabs

### 📸 Screenshots / Videos

![image](https://user-images.githubusercontent.com/3679022/113310780-f96d0a80-92de-11eb-8f7d-24f49c53a6d4.png)

### ▶ Steps to Reproduce

1. Go in creative mode
2. Search for any stone slab

### ✔ Expected Behavior

![image](https://user-images.githubusercontent.com/3679022/119575166-fba68f00-bd8c-11eb-880d-a5a1fcada0a7.png)

### ❌ Actual Behavior

![image](https://user-images.githubusercontent.com/3679022/119575212-0d883200-bd8d-11eb-87ea-5460e035b398.png)

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT at b7f4ffa

### 💬 Anything else we should know?

https://discord.com/channels/728280425255927879/728284682646716416/827188850194645073

**Comment by MonoAdrian23** [comment]
I can't craft it to with fast recipe.
There is no recipe example for it

**Comment by joserobjr** [comment]
> I can't craft it to with fast recipe.
> There is no recipe example for it

Can you craft with `stonecutter_block`?

**Comment by MonoAdrian23** [comment]
I try

**Comment by MonoAdrian23** [comment]
With stonecutter, all works perfectly

**Comment by DesertSoldier43** [comment]
To get them, do /give @s (ID)

**Comment by MonoAdrian23** [comment]
> To get them, do /give @s (ID)

I know, but this answer is no issue fix xd

**Comment by joserobjr** [comment]
Solved! xD
