### ISSUE TITLE
When the server is stopped, players do not get kicked off properly.

### ISSUE THREAD

**Issue by RealTriassic** [PowerNukkit/PowerNukkit#1029]
# 🐞 I found a bug
This possibly could also be a incompatibility with Waterdog, it's possible.

### ▶ Steps to Reproduce

1. Stop the server with players being on the server. (also try this twice with Waterdog.)
2. Players will not be kicked off the server.

### ✔ Expected Behavior

Players get kicked off the server, just exactly how they should be.

### ❌ Actual Behavior

Players "stay on the server" on the client-side, but just as if the server was not responding.

### 📋 Debug information

* PowerNukkit version: This server is running Nukkit 1.4.0.0-PN-SNAPSHOT (git-b7f4ffa) 「PowerNukkit」 implementing API version 1.0.12 for Minecraft: BE v1.16.210 (protocol version 428)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by joserobjr** [comment]
Thank you for the report.

This issue seems to be the same as #912, so I'm closing as duplicated
