### ISSUE TITLE
Prismarine Crystals / Itemframe

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1032]
# 🐞 I found a bug
 If you place Prismarine Crystals in a Itemframe, the structure isnt correct.

### 📸 Screenshots / Videos
 
![image](https://user-images.githubusercontent.com/31969146/114317358-1921e100-9ade-11eb-9c73-b652ff6fcc99.png)

### ▶ Steps to Reproduce

1. Place a Itemframe and put Prismarine Crystals in this Frame.
2. Now you can see a Bug Block Structure

### 📋 Debug information

* PowerNukkit version: (b7f4ffa)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
![20210405_101235.jpg](https://user-images.githubusercontent.com/59027482/113553212-b5884700-95f7-11eb-85c7-5572f92c7ecc.jpg)

**Comment by joserobjr** [comment]
Thank you for reporting!
