### ISSUE TITLE
Meta Items

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1038]
# 🐞 I found a bug
 All Items with Meta doesn't work
You can't move this in you're inventory or place them.
For Example, place a Spruce Sapling, it changes to Oak Sapling
RoseBush changes to Sunflower 
All Wood items changes to oak wood

### ▶ Steps to Reproduce

1. Place Item with MetaID
2. You can't move this Item or place them
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-c1e074f)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
@joserobjr Sorry for this Ping but I hope you can try all you're best.
Many servers are unplayable

**Comment by Gabriel8579** [comment]
Fixed at #1040 c1e074fbd771b85937e3c1547d5879296aeccdd8
