### ISSUE TITLE
All Stone Slabs are not available

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1045]
# 🐞 I found a bug
 It's not craftable, it's not in Creative Tab

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-3bb9763)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
![Screenshot_20210419-154011_Minecraft.jpg](https://user-images.githubusercontent.com/59027482/115245786-958f7200-a125-11eb-9c71-7ec2948f410d.jpg)

**Comment by joserobjr** [comment]
Thank you for the report.

I'm closing it as duplicated of #1027 but it was just fixed in #1082 :)
