### ISSUE TITLE
Cobblestone Walls

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1046]
# 🐞 I found a bug
 Try to place Cobblestone Walls but it changes to a Stonebrick Wall

### ▶ Steps to Reproduce

1. See link youtube
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-3bb9763)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
https://youtu.be/2OI0BZBYtrw

**Comment by Gabriel8579** [comment]
I couldn't reproduce it, might be fixed at #1050. Closing as stale
