### ISSUE TITLE
Banner Crafting 

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1054]
# 🐞 I found a bug
 If you try to craft a Banner, the client crashs

### ▶ Steps to Reproduce

1. try to craft a banner
2. now the client crashs complete

### 📋 Debug information

* PowerNukkit version: (git-3bb9763)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by joserobjr** [comment]
Hi, thank you for the report,

I tested with 1.4.0.0-PN-SNAPSHOT at b4edc6631cecfd8e71f75fd1a6cce7c8f046a19f but I could not reproduce the issue, I think it is already fixed.

Can you check if this still happens with this build?
https://builds.powernukkit.org/buildConfiguration/PowerNukkit_Mc1_16_220/303?buildTab=artifacts
Direct link: https://builds.powernukkit.org/repository/download/PowerNukkit_Mc1_16_220/303:id/powernukkit-1.4.0.0-PN-SNAPSHOT-shaded.jar

**Comment by MonoAdrian23** [comment]
I have tested it and all works fine now. 
Thank you very much

**Comment by joserobjr** [comment]
Thank you for letting us know :)
