### ISSUE TITLE
The Ban and Kick disconnect screen doesnt work. Same with the rejoin screen, it doesnt display the reason

### ISSUE THREAD

**Issue by DesertSoldier43** [PowerNukkit/PowerNukkit#1059]
# 🐞 I found a bug
When I do /ban >Username> <reason> and it kicks them/bans them when they disconnect from the server, it doesn't display the reason and if it is a ban/kick. It just shows Disconnected from Server and if it is a ban, they rejoin, it says in console

←[36m16:03:56←[m [←[34mINFO ←[m] [DesertSoldier43: Banned player DesertSoldier43]
←[36m16:09:49←[m [←[34mINFO ←[m] DesertSoldier43[/0:0:0:0:0:0:0:1:59865] logged out due to You are banned. Reason: This doesnt work

![Minecraft 5_16_2021 4_13_46 PM](https://user-images.githubusercontent.com/75911941/118415872-b59d4d00-b661-11eb-9370-d5d17c8cc7a2.png)
![Minecraft 5_16_2021 4_13_28 PM](https://user-images.githubusercontent.com/75911941/118415875-b635e380-b661-11eb-96fd-4517290fdc63.png)
![C__windows_system32_cmd exe 5_16_2021 4_15_19 PM](https://user-images.githubusercontent.com/75911941/118415949-175db700-b662-11eb-8d66-9acfa670df02.png)

### ▶ Steps to Reproduce

1. Run command 'ban, or kick'
2. do the essential things for example (/kick DesertSoldier43 test) or (/ban DesertSoldier43 test
3. wait for disconnect and see what it says. I am using the latest version

### ✔ Expected Behavior

it doesn't display reason

### 💬 Anything else we should know?

I am using a resource pack that changes the Minecraft Bedrock chat UI. It makes it like Java. It is nothing with resource packs as I have disabled ALL and it still didn't work.

**Comment by DesertSoldier43** [comment]
> Hey @DesertSoldier43, thank you for the report!
> 
> ⚠️ **I could not find which PowerNukkit version you are using from your message.** ⚠️
> 
> Please, run the command: `/debugpaste` it will generate a link, send us this link replying this issue.
> It's an important step to get your issue resolved.
> 
> Don't say _latest_ or _current version_, we support different versions and your latest may not be the same latest as our, and your latest will not be the same latest in the future, so please, use a fixed version.
> 
> Thank you 👍

debugpastes\debugpaste-2021-05-16T16.20.11.161-0700.zip

**Comment by Gabriel8579** [comment]
> > Hey @DesertSoldier43, thank you for the report!
> > ⚠️ **I could not find which PowerNukkit version you are using from your message.** ⚠️
> > Please, run the command: `/debugpaste` it will generate a link, send us this link replying this issue.
> > It's an important step to get your issue resolved.
> > Don't say _latest_ or _current version_, we support different versions and your latest may not be the same latest as our, and your latest will not be the same latest in the future, so please, use a fixed version.
> > Thank you 👍
> 
> debugpastes\debugpaste-2021-05-16T16.20.11.161-0700.zip

You should send the link that it provides

**Comment by Gabriel8579** [comment]
But probably this will be solved at #1033

**Comment by DesertSoldier43** [comment]
it doesn't show  a link in the home PC

**Comment by DesertSoldier43** [comment]
nvm, found it. I had to to debugpaste upload last

https://debugpaste.powernukkit.org/pastes/PN45793e94

**Comment by joserobjr** [comment]
1.4.0.0-PN-SNAPSHOT 0a92c3f

**Comment by Gabriel8579** [comment]
Fixed at #1033. Closing
