### ISSUE TITLE
Will you add Nukkit 2.0 to your version?

### ISSUE THREAD

**Issue by LucGamesYT** [PowerNukkit/PowerNukkit#106]
Will you add Nukkit 2.0 to your version?

**Comment by RORIdev** [comment]
Discussion on #107

**Comment by joserobjr** [comment]
Yes, it's a hard merge but I'm doing it, I'm going to keep it separated for a while too because it will need a lot of testing.

**Comment by LucGamesYT** [comment]
Nice :)

**Comment by joserobjr** [comment]
It's being worked on #127 and later on #107 .

Leaving open so people can find the answer quicker
