### ISSUE TITLE
All Stoneslabs are not avaiable

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1060]
# 🐞 I found a bug
 In creative mode, there are no Stoneslabs

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-b4edc66)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
![Screenshot_2021-05-17-06-24-56-146_com.mojang.minecraftpe.jpg](https://user-images.githubusercontent.com/59027482/118432751-b1147b00-b6d9-11eb-8444-56e9dda00171.jpg)

**Comment by joserobjr** [comment]
Thank you for the report. This issue is already being tracked at #1027
