### ISSUE TITLE
Grindstone Dont Work

### ISSUE THREAD

**Issue by TheDiego845** [PowerNukkit/PowerNukkit#1061]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Put a Grindstone
2. Click on Grindstone
3. Try to use and the item return to you

### ✔ Expected Behavior
Grindstone works

### ❌ Actual Behavior
Grindstone dont work

### 📋 Debug information

* PowerNukkit version: git 5e097f0
* Debug link: https://debugpaste.powernukkit.org/pastes/PNef7841aa/ 
* Timings link (if relevant):

**Comment by joserobjr** [comment]
What do you mean by Whetstone? Can you add a screenshot of it?

**Comment by TheDiego845** [comment]
![image](https://user-images.githubusercontent.com/69425536/118668093-d9dd6300-b7f4-11eb-98a2-042d0d3e1e67.png)

**Comment by Gabriel8579** [comment]
Fixed at #1064 closing.
