### ISSUE TITLE
smithing table doesnt work with enchantments

### ISSUE THREAD

**Issue by Superzock3003** [PowerNukkit/PowerNukkit#1062]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Place a smithing table
2. enchant a diamond tool
3. Put it with the netherite ingot into the smithing table

### ✔ Expected Behavior

You will get a netherite tool with this enchantment

### ❌ Actual Behavior

You will get the diamond tool and the netherite ingot back

### 📋 Debug information

* PowerNukkit version:  1ed3be2
* Debug link: ✍
* Timings link (if relevant): ✍ 

### 💬 Anything else we should know?
You can also put any item in the netherite slot

**Comment by joserobjr** [comment]
Oh no 😭
