### ISSUE TITLE
Lapis/Cauldron

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1068]
# 🐞 I found a bug
 I try to use Lapis in a cauldron
But the water in Cauldron is Green and the leather item is green with lapis

### ▶ Steps to Reproduce

1. Fill Cauldron with Water
2. Use Lapis
3. Now you can see, water is green
4. The Leather Item is green when you try to coloured it

### 📋 Debug information

* PowerNukkit version: (git-0198a40)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by joserobjr** [comment]
Thank you for reporting
