### ISSUE TITLE
SmithingTable Bug 

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1075]
# 🐞 I found a bug
 You cant upgrade a diamond shovel and a diamond axe

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-030cc24)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by joserobjr** [comment]
Thank you for the report!
