### ISSUE TITLE
Black Dye/Ink Sac

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1077]
# 🐞 I found a bug
 Its not possible to craft black dye with ink sak

### ▶ Steps to Reproduce

1. Use a Ink Sac in Survival Mode
2. Try to craft Black Dye
3. Now you can see, isnt possible

### 📋 Debug information

* PowerNukkit version: (git-030cc24)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by joserobjr** [comment]
Thank you for reporting!
