### ISSUE TITLE
The item IDs on Nukkit are not the same as Bedrock or Java

### ISSUE THREAD

**Issue by DesertSoldier43** [PowerNukkit/PowerNukkit#1078]
# 🐞 I found a bug

### 📸 Screenshots / Videos

![image](https://user-images.githubusercontent.com/75911941/119246016-a707d780-bb32-11eb-9e78-a84486d90141.png)
![image](https://user-images.githubusercontent.com/75911941/119246022-b555f380-bb32-11eb-821c-694ef56bae7e.png)
![image](https://user-images.githubusercontent.com/75911941/119246030-c141b580-bb32-11eb-876a-bdf3bf2d8e62.png)
![image](https://user-images.githubusercontent.com/75911941/119246096-73797d00-bb33-11eb-9c8b-eae3181ff357.png)

### ▶ Steps to Reproduce

1 Download this plugin: https://cloudburstmc.org/resources/itemnav.648/
2. install it.
3. Get activator rail and compare it to this website:https://www.digminecraft.com/lists/item_id_list_win10.php OR https://www.digminecraft.com/lists/item_id_list_pc.php
4. See the id

### ✔ Expected Behavior

Blocks wont be mistaken with others

### ❌ Actual Behavior

it replaces the blocks from a 1.12 world

### 📋 Debug information

https://debugpaste.powernukkit.org/pastes/PNeccb1a54

**Comment by DesertSoldier43** [comment]
> Hey @DesertSoldier43, thank you for the report!
> 
> ⚠️ **I could not find which PowerNukkit version you are using from your message.** ⚠️
> 
> Please, run the command: `/debugpaste` (legacy) or `/debugpaste upload` (1.4.0.0-PN+) it will generate a link, send us this link replying this issue.
> It's an important step to get your issue resolved.
> 
> Don't say _latest_ or _current version_, we support different versions and your latest may not be the same latest as our, and your latest will not be the same latest in the future, so please, use a fixed version.
> 
> Thank you 👍

https://debugpaste.powernukkit.org/pastes/PNeccb1a54

**Comment by joserobjr** [comment]
Hello, thank you for the report.

But the information provided by digminecraft is incorrect. Please refer to the official Minecraft wiki for ids:
https://minecraft.fandom.com/wiki/Activator_Rail#ID

Here's the list with all Bedrock Edition block and item IDs:
https://minecraft.fandom.com/wiki/Bedrock_Edition_data_values#Block_IDs

**Comment by DesertSoldier43** [comment]
o LMFAO. But can you change the id to  java just so we can convert maps
