### ISSUE TITLE
Wrong item name

### ISSUE THREAD

**Issue by AntonPPDS** [PowerNukkit/PowerNukkit#1083]
# 🐞 I found a bug
When getting the name of an item, I get an incorrect one. At the moment I only noticed this with dyes, but there may be other items with the wrong name.

### ▶ Steps to Reproduce

1. Use Item.getName() or something is using this method, i.e. **/give self white_dye**
2. You see that item name is wrong (actual item: white dye; name: brown dye)

### 📸 Screenshots / Videos
![image](https://user-images.githubusercontent.com/60366294/119617453-8bd6e980-be0a-11eb-8e9c-d7b3d8d8cfb7.png)

### 📋 Debug information

* PowerNukkit version: https://github.com/PowerNukkit/PowerNukkit/commit/e1a2217efc8a5e28df830e28033c5a74eb9255b0

**Comment by joserobjr** [comment]
Thank you for reporting!
