### ISSUE TITLE
Written Books cant be signed

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1090]
# 🐞 I found a bug
 You cant sign a written book

### ▶ Steps to Reproduce

1. Choose a Written Book
2. Try to sign it
3. The Sign window is closed a little bit buggy and the book isnt signed

### 📋 Debug information

* PowerNukkit version: (git-bf36ff7)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by LoboMetalurgico** [comment]
Fixed in #1194
