### ISSUE TITLE
/enchant wrong output message

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1102]
# 🐞 I found a bug
 If you use /enchant name id level 
It says enchant successful  %1$s

### ▶ Steps to Reproduce

1. Run command '/enchant name id level'
2. now you can see this bugmessage
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-2d28005)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by joserobjr** [comment]
Thank you for the report. Which language is configured in your server?

**Comment by MonoAdrian23** [comment]
I have choose german language

**Comment by LoboMetalurgico** [comment]
Fixed in #1103
