### ISSUE TITLE
minecarts bug in the ground after rejoin

### ISSUE THREAD

**Issue by Superzock3003** [PowerNukkit/PowerNukkit#1104]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Place a rail
2. Place a minecart on the rail
3. Break the rail
4. Rejoin

### ✔ Expected Behavior
Minecart is on the same hight

### ❌ Actual Behavior
Minecart bugs into the down

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT (git-ce54e92)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
Yes, its the same with ArmorStands

**Comment by GoodLucky777** [comment]
Duplicated with #614
