### ISSUE TITLE
Unknown plugin dependency error log problem

### ISSUE THREAD

**Issue by GoodLucky777** [PowerNukkit/PowerNukkit#1113]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Load the plugin that have dependency without dependency
2. You will see the log `[FATAL] Could not load plugin "SomePlugin": Unknown dependency`

### ✔ Expected Behavior

Log the dependency which is missing

### ❌ Actual Behavior

It doesn't log the dependency

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN (be41f4538b8b3bd25e4929996c1c0274657a08d3)
* Debug link: -
* Timings link (if relevant): - 

### 💬 Anything else we should know?

https://github.com/PowerNukkit/PowerNukkit/blob/19aabb93a5402075f509910e0709e43f280042be/src/main/java/cn/nukkit/plugin/PluginManager.java#L269-L270

**Comment by MonoAdrian23** [comment]
I havent this issue. 
You must install the Plugin depends for some Plugins. 
For example: Plotsquared cant load without depend Plugin like Fawe. 
Install the depend and this error is fixed.

**Comment by GoodLucky777** [comment]
I know dependency load error can be fixed with installing dependency but it doesn't show what dependency is missing in error log. In error log there is dependency parameter, but translated string doesn't have it
