### ISSUE TITLE
Bedrock 1.17 Support

### ISSUE THREAD

**Issue by LoboMetalurgico** [PowerNukkit/PowerNukkit#1114]
# ❇ Feature Request
Minecraft 1.17 released on June, 8th

#### Urgent Priority

* [x] Update the Protocol #1116

#### Known Bugs

* [ ] Teleport inside boat causes infinite teleports
* [ ] Passing the boat over the Victoria Regia makes it visually disappear in the client
* [ ] If the player skin is buggy on the client, several players on the server will not see the player and nametag
* [ ] Seapicke is not able to put more than one on the same block if there is a block on top and you click on the top of the hitbox
* [ ] Double chest opens with a block on top of it if you have a block in your hand

#### Information

https://minecraft.fandom.com/wiki/Bedrock_Edition_1.17.0
https://feedback.minecraft.net/hc/en-us/articles/4402427632013

#### Server and Tools

Vanilla server: https://www.minecraft.net/en-us/download/server/bedrock/ (Currently at 1.17.0.03)
Packet inspections: https://github.com/PowerNukkit/Bedrock-ProxyPass (Currently incompatible with 1.17)
Packet inspections (harder alternative): https://www.wireshark.org/
Vanilla level editor: https://www.universalminecrafteditor.com/ (may be used to see how the game persist stuff, helps to understand the packets)

**Comment by joserobjr** [comment]
Actually, I'm reopening it to add the new features to the list

**Comment by DeeRenjie** [comment]
Bedrock 1.17.30 Support

**Comment by MonoAdrian23** [comment]
Be patient

**Comment by alikindsys** [comment]
Supported since `1.5.0.0-PN`. Closing the issue.
