### ISSUE TITLE
Soul campfire item is being rendered as glow_frame

### ISSUE THREAD

**Issue by DesertSoldier43** [PowerNukkit/PowerNukkit#1130]
# 🐞 I found a bug

### 📸 Screenshots / Videos

![image](https://user-images.githubusercontent.com/75911941/121735153-994acf80-caaa-11eb-8320-df7f951eb6d2.png)

### ▶ Steps to Reproduce

Place Glow Item Frame 
watch what it places (Soul Camp Fire)

### ✔ Expected Behavior

Places Glow Item Frame

### ❌ Actual Behavior

Places Soul Camp Fire

### 📋 Debug information

*1.17.0: ✍
* https://debugpaste.powernukkit.org/pastes/PNb4e5b8c6: ✍

**Comment by DesertSoldier43** [comment]
https://debugpaste.powernukkit.org/pastes/PNb4e5b8c6

**Comment by joserobjr** [comment]
I thought it wasn't obtainable yet lol

**Comment by joserobjr** [comment]
```
/give @p soul_campfire
```
gives you a soul_campfire but it is being shown as glow_frame instead

**Comment by joserobjr** [comment]
Also affecting end_crystal
