### ISSUE TITLE
Unable to Initialize main class cn.nukkit.Nukkit

### ISSUE THREAD

**Issue by foxysy** [PowerNukkit/PowerNukkit#1142]
Hi all. I'm not an expert with Minecraft server and I need a hand with starting my server. After some Java updates and searches on internet I haven't found a solution for my problem. When I start up the server it says to me the following:
Error: Unable to initialize main class cn.nukkit.Nukkit
Caused by: java.lang.NoClassDefFoundError: joptsimple/OptionSpec
Press any key to continue...

Server does not create any file, I have only the server jar file, a Thermos 1.7.10 libraries that I downloaded in the hope it can help (but nothing) and a bat with: 
@echo off
java -Xms1G -Xmx1G -jar server2.jar
pause

I hope someone can help me. Thanks you

**Comment by foxysy** [comment]
I can't run any command so I can't put here the debug. The version that I downloaded is "powernukkit - 1.5.0.0-PN.jar"
Thanks

**Comment by AntonPPDS** [comment]
When you download a snapshot you have to choose *-shaded one.
![image](https://user-images.githubusercontent.com/60366294/122259513-f1366b80-ceda-11eb-879f-ac50649101e5.png)

**Comment by foxysy** [comment]
Thanks. I've just downloaded the stable one on power nukkit website. I don't know if it's the same but I'll try with the shaded when I go home.

**Comment by Gabriel8579** [comment]
> Thanks. I've just downloaded the stable one on power nukkit website. I don't know if it's the same but I'll try with the shaded when I go home.

It worked?

**Comment by Gabriel8579** [comment]
As there was no response, I will treat it as if it worked, closing as resolved. If necessary, please open another issue
