### ISSUE TITLE
Shears cannot cut spider webs

### ISSUE THREAD

**Issue by whes1015** [PowerNukkit/PowerNukkit#1148]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Scissors cannot cut spider webs

### 📋 Debug information

* PowerNukkit version:1.5.1.0-PN-20210611.204612-1 ✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MrRazamataz** [comment]
Do you mean shears?
