### ISSUE TITLE
Offand Shield is shown not correctly

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1156]
# 🐞 I found a bug
 If you hold a shield in Offhand, it doesnt display correctly. 
This bug is happens not all times. 
I dont know why it happens. 
If you break blocks with tools like diamond pickaxe, the shield has the same movement animation like diamond pickaxe

### ▶ Steps to Reproduce

1. Take a Shield in Offhand
2. Hopefully this bug appears
3. Now you can see the Bug in my Picture

### 📋 Debug information

* PowerNukkit version: (git-97c64ce)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
![IMG_20210625_120723.jpg](https://user-images.githubusercontent.com/59027482/123520577-a1f9f300-d6b1-11eb-9d37-61572f105b04.jpg)

**Comment by IWareQ** [comment]
This is Minecraft Bug!

**Comment by MonoAdrian23** [comment]
No i dont think so
It happens only in Nukkit and Powernukkit.

**Comment by joserobjr** [comment]
This is odd because I could not reproduce it

**Comment by IWareQ** [comment]
> No i dont think so
> It happens only in Nukkit and Powernukkit. 
> 

This is a Minecraft bug, because I have now tested the official core from the Minecraft developers, and there is also a problem
