### ISSUE TITLE
Random Memory Leak?

### ISSUE THREAD

**Issue by FlamingKnight** [PowerNukkit/PowerNukkit#1159]
# 🐞 I found a bug
Got a random error saying the finalizer failed to start, this is the first time it happened

### ▶ Steps to Reproduce
No idea

### 📋 Debug information

* PowerNukkit version: ✍Nukkit 1.5.0.0-PN (git-97c64ce) 「PowerNukkit」 implementing API version 1.0.12 for Minecraft: BE v1.17.0 (protocol version 440)

### 💢 Crash Dump, Stack Trace and Other Files
The other INFOs are from a discord channel
```java
27.06 02:54:26 [Server] INFO [5FrameStudiosSurvivalCore]: GamesAreEasy500 issued command: /anvil
27.06 02:54:28 [Server] INFO [5FrameStudiosSurvivalCore]: BootheBoys issued command: /shop
27.06 02:56:13 [Server] INFO   BootheBoys: <@!333247135380275200> we all disconnected?
27.06 02:56:13 [Server] INFO   GamesAreEasy500: oh everyone did? i thought it was my bad internet
27.06 02:56:13 [Server] FATAL --------- The finalizer thread didn't complete in time! ---------
27.06 02:56:13 [Server] INFO This detection means that the finalizer thread may be stuck and
27.06 02:56:13 [Server] INFO RAM memory might be leaking!
27.06 02:56:13 [Server] INFO - https://github.com/PowerNukkit/PowerNukkit/issues/new
27.06 02:56:13 [Server] INFO ---------------- ForcedFinalizer ----------------
27.06 02:56:13 [Server] INFO Attempted to dump a null thread!
27.06 02:56:13 [Server] INFO -------------------------------------------------
27.06 02:56:15 [Server] INFO   BootheBoys: Yeah the entire server is down
27.06 02:56:22 [Server] INFO   BootheBoys: and flaming is offline...
27.06 02:56:28 [Server] WARN The ForcedFinalizer has finished
27.06 02:56:39 [Server] INFO   GamesAreEasy500: oof
```

### 💬 Anything else we should know?
Plugins used are a custom one by myself, and Wode's generator plugins along with FAWE, none of them threw any errors

**Comment by FlamingKnight** [comment]
New update, got the error again this morning when I woke up and it has a lot more information!
27.06 15:03:13 [Server] INFO    FlamingKnight08: Test
27.06 15:03:13 [Server] INFO    MisledWater79: Test
27.06 15:03:13 [Server] FATAL --------- The finalizer thread didn't complete in time! ---------
27.06 15:03:13 [Server] INFO This detection means that the finalizer thread may be stuck and
27.06 15:03:13 [Server] INFO RAM memory might be leaking!
27.06 15:03:13 [Server] INFO - https://github.com/PowerNukkit/PowerNukkit/issues/new
27.06 15:03:13 [Server] INFO ---------------- ForcedFinalizer ----------------
27.06 15:03:13 [Server] INFO Current Thread: ForcedFinalizer
27.06 15:03:13 [Server] INFO PID: 8156 | Suspended: false | Native: false | State: WAITING
27.06 15:03:13 [Server] INFO Stack:
27.06 15:03:13 [Server] INFO java.lang.Object.wait(Native Method)
27.06 15:03:13 [Server] INFO java.lang.Thread.join(Thread.java:1252)
27.06 15:03:13 [Server] INFO java.lang.Thread.join(Thread.java:1326)
27.06 15:03:13 [Server] INFO java.lang.ref.Finalizer$1.run(Finalizer.java:136)
27.06 15:03:13 [Server] INFO java.lang.ref.Finalizer$1.run(Finalizer.java:127)
27.06 15:03:13 [Server] INFO java.security.AccessController.doPrivileged(Native Method)
27.06 15:03:13 [Server] INFO java.lang.ref.Finalizer.forkSecondaryFinalizer(Finalizer.java:126)
27.06 15:03:13 [Server] INFO java.lang.ref.Finalizer.runFinalization(Finalizer.java:150)
27.06 15:03:13 [Server] INFO java.lang.Runtime.runFinalization0(Native Method)
27.06 15:03:13 [Server] INFO java.lang.Runtime.runFinalization(Runtime.java:713)
27.06 15:03:13 [Server] INFO java.lang.System.runFinalization(System.java:1017)
27.06 15:03:13 [Server] INFO cn.nukkit.utils.Watchdog.lambda$checkFinalizer$0(Watchdog.java:51)
27.06 15:03:13 [Server] INFO cn.nukkit.utils.Watchdog$$Lambda$316/1550787619.run(Unknown Source)
27.06 15:03:13 [Server] INFO java.lang.Thread.run(Thread.java:748)
27.06 15:03:13 [Server] INFO -------------------------------------------------
27.06 15:03:13 [Server] WARN  A task raised an exception. Task: com.nukkitx.network.raknet.RakNetServer$$Lambda$325/1931585368@1b785658
27.06 15:03:13 [Server] INFO java.lang.NullPointerException: null
27.06 15:03:13 [Server] INFO at com.nukkitx.network.raknet.RakNetSession.initHeapWeights(RakNetSession.java:180) ~[custom.jar:?]
27.06 15:03:13 [Server] INFO at com.nukkitx.network.raknet.RakNetSession.deinitialize(RakNetSession.java:146) ~[custom.jar:?]
27.06 15:03:13 [Server] INFO at com.nukkitx.network.raknet.RakNetSession.close0(RakNetSession.java:594) ~[custom.jar:?]
27.06 15:03:13 [Server] INFO at com.nukkitx.network.raknet.RakNetSession.close(RakNetSession.java:581) ~[custom.jar:?]
27.06 15:03:13 [Server] INFO at com.nukkitx.network.raknet.RakNetSession.tick(RakNetSession.java:422) ~[custom.jar:?]
27.06 15:03:13 [Server] INFO at com.nukkitx.network.raknet.RakNetSession.onTick(RakNetSession.java:417) ~[custom.jar:?]
27.06 15:03:13 [Server] INFO at com.nukkitx.network.raknet.RakNetServer.lambda$onTick$1(RakNetServer.java:129) ~[custom.jar:?]
27.06 15:03:13 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [custom.jar:?]
27.06 15:03:13 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [custom.jar:?]
27.06 15:03:13 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [custom.jar:?]
27.06 15:03:13 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [custom.jar:?]
27.06 15:03:13 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [custom.jar:?]
27.06 15:03:13 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
27.06 15:03:13 [Server] INFO  [CONSOLE: Saving...]
27.06 15:03:14 [Server] INFO  [CONSOLE: Saved the world]
27.06 15:03:14 [Server] INFO  [CONSOLE: Stopping the server]
27.06 15:03:14 [Server] INFO  logged out due to Server closed
27.06 15:03:14 [Server] WARN  A task raised an exception. Task: com.nukkitx.network.raknet.RakNetSession$$Lambda$465/740781660@7deb9f5d
27.06 15:03:14 [Server] INFO java.lang.NullPointerException: null
27.06 15:03:14 [Server] INFO at com.nukkitx.network.raknet.RakNetSession.initHeapWeights(RakNetSession.java:180) ~[custom.jar:?]
27.06 15:03:14 [Server] INFO at com.nukkitx.network.raknet.RakNetSession.deinitialize(RakNetSession.java:146) ~[custom.jar:?]
27.06 15:03:14 [Server] INFO at com.nukkitx.network.raknet.RakNetSession.close0(RakNetSession.java:594) ~[custom.jar:?]
27.06 15:03:14 [Server] INFO at com.nukkitx.network.raknet.RakNetSession.lambda$close$0(RakNetSession.java:583) ~[custom.jar:?]
27.06 15:03:14 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [custom.jar:?]
27.06 15:03:14 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [custom.jar:?]
27.06 15:03:14 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [custom.jar:?]
27.06 15:03:14 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [custom.jar:?]
27.06 15:03:14 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [custom.jar:?]
27.06 15:03:14 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by IWareQ** [comment]
Please, use `/debugpaste upload` and pastebin.com

**Comment by FlamingKnight** [comment]
But I can't when it crashes the server, can I?

**Comment by roridev** [comment]
Can you check if this error happens without the custom plugin. We hadn't had reports with wode's world generation plugins causing a memory leak in pn for quite some time, and that plugin is widely used by the community. Same with FAWE. The only weird unknown is the custom plugin.

**Comment by FlamingKnight** [comment]
I have no idea how to check if it is a plugin or PN, the plugin never has anything to do with threads and managing them, and it was really random, I used the plugin all the time before as well and have never ran into this error, on the same machine which gave the error just recently

**Comment by roridev** [comment]
Thats exactly why i asked to remove the plugin, so that if this error still happens, this is a PN issue, otherwise its a plugin issue. Memory leaks can be caused by faulty user-space(plugin) logic. Since neither wode's or fawe ever caused that issue, i'm asking to check on the custom one (which we do not have access to), I'll also ask which build of fawe are you using so we can check that for you.

**Comment by FlamingKnight** [comment]
Ok, I'll look more into it, thanks for the response! Here's the FAWE version, though no commands were run for it in both cases FastAsyncWorldEdit v19.03.29-d13b946-1257-22.0.14, I'll try it with and without my plugin more but it might take a while for me to completely see

**Comment by roridev** [comment]
Sure, no rush

**Comment by FlamingKnight** [comment]
After a while I'm not getting anything and am assuming it was some bug more so with the machine we used at the time, sorry for the bother!
