### ISSUE TITLE
WorldEdit does not automatically update blocks

### ISSUE THREAD

**Issue by easeray** [PowerNukkit/PowerNukkit#1160]
# 🐞 Nukkit does not automatically update blocks(like sand or any others)

When I used the `brush` function of `WorldEdit` to generate sand blocks,the sand blocks didn't fall to the ground.
But when I destroyed one of the sand blocks, they fell normally.
### 📸 Screenshots / Videos

![Screenshot_20210627_180210](https://user-images.githubusercontent.com/85833388/123541966-94a83b80-d779-11eb-9225-8e673dc78fee.jpg)

### ▶ Steps to Reproduce

1. Use `/br cyl sand 3 2`
2. Use the brush
3. the sand blocks float in the air

### ✔ Expected Behavior

the sand blocks can automatically drop.

### ❌ Actual Behavior

the sand blocks are floating in the air

### 📋 Debug information

* PowerNukkit version: Nukkit 1.5.0.0-PN
* Debug link: https://debugpaste.powernukkit.org/pastes/PN5bb086e1
* Timings link (if relevant): 

### 💬 Anything else we should know?

the download link of `worldedit`:https://nukkitx.com/resources/fastasyncworldedit.30/

**Comment by IWareQ** [comment]
This is done so that when building something, the blocks do not fall but remain in their places

**Comment by easeray** [comment]
> 这样做是为了在建造东西时，块不会掉落而是保持在它们的位置

but i should the sand block automatically drop,this can help me bulid the lands or mountains

**Comment by easeray** [comment]
So how to solve this problem. It is difficult to contact the author. The link of `World Edit` has been deleted.

**Comment by MonoAdrian23** [comment]
FastAsyncWorldEdit?

**Comment by easeray** [comment]
> FastAsyncWorldEdit?

yes,FAWE(for nukkit) hasn't been updated for a long time.
