### ISSUE TITLE
Contiguous rails don't activate

### ISSUE THREAD

**Issue by mercadanteus** [PowerNukkit/PowerNukkit#1161]
***Description of the bug:
If you activate a propulsor rail with a redstone torch, other contiguous propulsor rails don´t get activated

### ▶ Steps to Reproduce
Simply install last stable or snapshot version (in my case) 1.5-PN-MC1.17.0-B80, and try to replicate the bug using 2 or more propulsor rails and a single redstone torch.

***Picture
![rail](https://user-images.githubusercontent.com/24380156/123568033-18b5ef80-d789-11eb-84e8-aeea8ea0d0b4.jpg)

### ✔ Expected Behavior
All rails should get activated

### ❌ Actual Behavior
Only the rail with the torch is activated

### 📋 Debug information
* PowerNukkit version: 1.5-PN-MC1.17.0-B80
* Debug link: https://debugpaste.powernukkit.org/pastes/PN2a3e39cd/
* Timings link (if relevant): ✍

**Comment by Gabriel8579** [comment]
Closing as duplicated by #908
