### ISSUE TITLE
The iron bucket milking bucket will disappear

### ISSUE THREAD

**Issue by whes1015** [PowerNukkit/PowerNukkit#1165]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1.The iron bucket milking bucket will disappear

### 📋 Debug information

* PowerNukkit version:1.5-PN-MC1.17.0-B80 ✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
If you use MobPlugin?

**Comment by whes1015** [comment]
I am using

> 如果你使用 MobPlugin？

I am using

**Comment by Superzock3003** [comment]
Its an Mobplugin Error

**Comment by MonoAdrian23** [comment]
Its a confirmed issue in MobPlugin. 
Only Gamemode Creative Buckets works

**Comment by GoodLucky777** [comment]
I fixed it in https://github.com/Nukkit-coders/MobPlugin/pull/231

**Comment by whes1015** [comment]
> 我在[Nukkit-coders/MobPlugin#231 中](https://github.com/Nukkit-coders/MobPlugin/pull/231)修復了它[](https://github.com/Nukkit-coders/MobPlugin/pull/231)

got it

**Comment by MonoAdrian23** [comment]
You can close this because its fixed
