### ISSUE TITLE
Can't open a backpack while riding a horse

### ISSUE THREAD

**Issue by whes1015** [PowerNukkit/PowerNukkit#1166]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Can't open a backpack while riding a horse

### 📋 Debug information

* PowerNukkit version: 1.5-PN-MC1.17.0-B80✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by Superzock3003** [comment]
Its an Mobplugin Error

**Comment by whes1015** [comment]
> 這是一個 Mobplugin 錯誤

!got it
