### ISSUE TITLE
Redstone comparator causes the server to crash

### ISSUE THREAD

**Issue by whes1015** [PowerNukkit/PowerNukkit#1182]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Redstone comparator causes the server to crash

### 📋 Debug information

* PowerNukkit version: 1.5.2.0-PN✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by Gabriel8579** [comment]
Can you provide the /debugpaste upload command result?

**Comment by FlamingKnight** [comment]
Is it the same as this? https://github.com/PowerNukkit/PowerNukkit/pull/1204

**Comment by roridev** [comment]
Duplicate of #1174. 
Will be solved by #1204.
