### ISSUE TITLE
Remove /reload command

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1195]
# ❇ Feature Request
 Many Softwares remove /reload from Core because this command can create damage with some plugins. 

Its a Feature Request

**Comment by FlamingKnight** [comment]
/reload can be a beneficial command, if you want you can ask someone to unregister it for you, there really is no good reason I can see to remove it, unless your staff don't know what they're doing

**Comment by MonoAdrian23** [comment]
Why i should ask for someone? 
Pocketmine haves remove this command too. 
90% of Cloudburst Plugins doesnt work with /reload
And i am my own Staff xd. 
At next, too much people creates a new server for beginner. 
Use /reload kills too much. 
Remove /reload is a better way to stop issues with unsupported plugins

**Comment by FlamingKnight** [comment]
I still don't see a problem with keeping it, what makes you keep on using it? Is there no way you can stop using it?

**Comment by MonoAdrian23** [comment]
This is not my Problem only. 
Newstarter Servers use /reload and kill her own plugins. 
I havent a Problem with /reload

**Comment by FlamingKnight** [comment]
Ok, I'll make a quick plugin for that since it still may be useful for other people

**Comment by MonoAdrian23** [comment]
I dont know which role you have here? 
But you cant understand this
