### ISSUE TITLE
Add Option for Disabling Standard Worlds

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1196]
# ❇ Feature Request
 Please add an Option for disabling Nukkits Standart Generators. 
Many users haves a owm generator and powernukkit/nukkit takes a while for new generators.

**Comment by MonoAdrian23** [comment]
Nope 
Not with self uploaded worlds

**Comment by FlamingKnight** [comment]
They should, if they don't it could be considered a bug, you can check your config.yml for the plugin to see what worlds it affects

**Comment by MonoAdrian23** [comment]
Many Users need a 1.16 Nether
See Discord please. 
And the normal nether is created with the 1.16 nether.

**Comment by FlamingKnight** [comment]
Are you asking to upgrade the nether to 1.16?

**Comment by MonoAdrian23** [comment]
No
Many user use chunks from a Java World. 
This works
And these players have now 2 Nethers but only 1 nether can exist. 
You need only 1 
It should be possible to disable by default

**Comment by FlamingKnight** [comment]
Well, the reason it works is because it was pre generated, there's no way to keep that generation in PowerNukkit since there's no 1.16 generation, you can add a world border for now while it's being worked on I suppose

**Comment by MonoAdrian23** [comment]
Oh man you cant understand. 
Forget it
