### ISSUE TITLE
You can craft only oak items

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1200]
# 🐞 I found a bug
 You cant craft, jungle planks etc. 
Each sort of wood shows only recipes for oak items

### ▶ Steps to Reproduce

1. Take jungle logs or, acadia or another
2. try to craft it in planks 
3. you see only the recipe for oak planks
4. 

### 📋 Debug information

* PowerNukkit version: (git-d33a577)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
![Screenshot_20210714-104233_Minecraft.jpg](https://user-images.githubusercontent.com/59027482/125593251-4d4141ac-2543-446f-99b5-b6d534f8057a.jpg)

**Comment by MonoAdrian23** [comment]
It happens too in the next snapshot

**Comment by joserobjr** [comment]
Thank you for reporting!
