### ISSUE TITLE
Blocks with gravity don't collide with waterlogged blocks

### ISSUE THREAD

**Issue by Kevin-Zhouu** [PowerNukkit/PowerNukkit#1207]
### ▶ Steps to Reproduce
When you place an anvil over slabs or stairs waterlogged it starts glitching and makes infinite sounds

### ✔ Expected Behavior
Doesn't make any sound
Thanks!

**Comment by Kevin-Zhouu** [comment]
https://debugpaste.powernukkit.org/pastes/PNc44368b6

**Comment by Kevin-Zhouu** [comment]
![image](https://user-images.githubusercontent.com/68810460/126036995-57f3c809-a52b-4d16-9826-b79fdad23496.png)

**Comment by alikindsys** [comment]
Replicated on 382d1ca34216992bb0210d2968642923c78ce941


https://user-images.githubusercontent.com/36565196/178397312-804e8111-ab1b-4ed3-9c2b-2e320ac841f3.mp4

**Comment by LoboMetalurgico** [comment]
Fixed in #1387
