### ISSUE TITLE
Can't download the latest version PN

### ISSUE THREAD

**Issue by yunzaixi** [PowerNukkit/PowerNukkit#1209]
I can't connect to
https://builds.powernukkit.org/buildConfiguration/PowerNukkit_Snapshots

from Macao

What the problems？I think it not my network problems.

**Comment by yunzaixi** [comment]
![捕获](https://user-images.githubusercontent.com/73321886/126061066-6e50b6eb-126e-49f1-ae6a-c5b4d1326c33.PNG)

**Comment by Plugner** [comment]
Did you try it today?

**Comment by Gabriel8579** [comment]
Working fine here...

https://builds.powernukkit.org/buildConfiguration/PowerNukkit_Snapshots/466
