### ISSUE TITLE
Catastrophe (minerals are not generated in newly loaded blocks)

### ISSUE THREAD

**Issue by whes1015** [PowerNukkit/PowerNukkit#1211]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. used wodeBetterVanillaGenerator-1.2.2

### 📋 Debug information

* PowerNukkit version: git-990135c✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
Delete VanillaGen and use the Nukkit Generator. 
Because its a Plugin Bug

**Comment by whes1015** [comment]
> Delete VanillaGen and use the Nukkit Generator.
> Because its a Plugin Bug

But how to deal with the loaded block

**Comment by MonoAdrian23** [comment]
Nukkit haves a good world with much more biomes and better performance (bugfree) 
Delete the VanillaGen world and the plugin and the Software generates his own world

**Comment by whes1015** [comment]
> Nukkit haves a good world with much more biomes and better performance (bugfree)
> Delete the VanillaGen world and the plugin and the Software generates his own world

But my current world has been around for a long time

**Comment by whes1015** [comment]
> Nukkit haves a good world with much more biomes and better performance (bugfree)
> Delete the VanillaGen world and the plugin and the Software generates his own world

Is there no other way?

**Comment by MonoAdrian23** [comment]
Nope

**Comment by whes1015** [comment]
> Nope

So sad

**Comment by MonoAdrian23** [comment]
BetterVanillaGen is only for world and nether. 
Whats the problem? 

Delete this worlds and use Nukkit Worlds.

**Comment by whes1015** [comment]
> BetterVanillaGen is only for world and nether.
> Whats the problem?
> 
> Delete this worlds and use Nukkit Worlds.

The loaded block cannot be connected to the newly loaded block

**Comment by MonoAdrian23** [comment]
There is a Open issue but Wode says me this plugin is not longer in development. 

Nukkit haves a much more better generation as this

**Comment by whes1015** [comment]
> Nukkit haves a much more better generation as this

I see, I have deleted it, but the error generated by the loaded block can no longer be eliminated

**Comment by MonoAdrian23** [comment]
When you delete the old worlds, no old blockload exist xd

**Comment by whes1015** [comment]
> When you delete the old worlds, no old blockload exist xd

But my current world already has a lot of buildings

**Comment by MonoAdrian23** [comment]
This blocks cant be loaded without the Plugin. 
Omg!!!!

**Comment by MonoAdrian23** [comment]
Delete VanillaGen

**Comment by whes1015** [comment]
> Delete VanillaGen

I have deleted

**Comment by whes1015** [comment]
> Delete VanillaGen

But all the players’ efforts were in vain

**Comment by TheDiego845** [comment]
Try using https://github.com/tuilakhanh/BetterVanillaGenerator

**Comment by whes1015** [comment]
> Try using https://github.com/tuilakhanh/BetterVanillaGenerator

I used 1.2.2

**Comment by whes1015** [comment]
> Try using https://github.com/tuilakhanh/BetterVanillaGenerator

That one is 1.2.1

**Comment by MonoAdrian23** [comment]
1.2.1 haves no biomes like mesa, jungle, etc

**Comment by whes1015** [comment]
> 1.2.1 haves no biomes like mesa, jungle, etc

What does this mean

**Comment by TheDiego845** [comment]
I prefer not to have biomes than to have no ores.

**Comment by whes1015** [comment]
> I prefer not to have biomes than to have no ores.

I have always used the 1.2.2 version and it is no problem when the protocol version is 440.

**Comment by MonoAdrian23** [comment]
Nice

- Ores
- 3 Sorts of Wood
- Rivers

Its all Positiv

- Memory Leak
- No Biomes
- Laggy and slow world gen
- No development

**Comment by whes1015** [comment]
> Nice
> 
> * Ores
> * 3 Sorts of Wood
> * Rivers
> 
> Its all Positiv
> 
> * Memory Leak
> * No Biomes
> * Laggy and slow world gen
> * No development

Should I use 1.2.1 or delete

**Comment by MonoAdrian23** [comment]
It doenst have any to do with protocol. 
Omg! 
What is happen here. 
Open a issue by Woder and not here. 
But Woder says much times!!!! 
This Plugin is not longer in Development!!!!!!!!!!!!!!!!!!!

**Comment by MonoAdrian23** [comment]
Use the Nukkit Normal Generator. 
Say it 4 Times

**Comment by whes1015** [comment]
> It doenst have any to do with protocol.
> Omg!
> What is happen here.
> Open a issue by Woder and not here.
> But Woder says much times!!!!
> This Plugin is not longer in Development!!!!!!!!!!!!!!!!!!!

I know it is not related to the agreement. I just want to explain that it worked normally before and ask the possible reasons for the problem now.

**Comment by whes1015** [comment]
> Use the Nukkit Normal Generator.
> Say it 4 Times

Got it

**Comment by MonoAdrian23** [comment]
Open a useless Issue by Woder. 
This is a Plugin Issue and this PLUGIN is not longer supported

**Comment by MonoAdrian23** [comment]
You can close this Issue.

**Comment by whes1015** [comment]
> Open a useless Issue by Woder.
> This is a Plugin Issue and this PLUGIN is not longer supported

How about woder`s other structure plugin

**Comment by whes1015** [comment]
> You can close this Issue.
of course

**Comment by MonoAdrian23** [comment]
Thanks 
And i can try to fix this plugin in a fork. 
Give me time for it

**Comment by whes1015** [comment]
> Thanks 
> And i can try to fix this plugin in a fork. 
> Give me time for it

Thanks

**Comment by MonoAdrian23** [comment]
All these Plugins creates Memory Leaks and the world loads very slowly. 
I hope Powernukkit haves a better codequality for it

**Comment by whes1015** [comment]
> All these Plugins creates Memory Leaks and the world loads very slowly. 
> I hope Powernukkit haves a better codequality for it

So I should delete all the wode`s plugin

**Comment by whes1015** [comment]
> All these Plugins creates Memory Leaks and the world loads very slowly. 
> I hope Powernukkit haves a better codequality for it

![Screenshot_2021-07-20-02-04-11-649_it.Ettore.raspcontroller.jpg](https://user-images.githubusercontent.com/44525760/126206122-104c5eb7-4bfd-40fb-94c2-758d345d34ef.jpg)

**Comment by whes1015** [comment]
> All these Plugins creates Memory Leaks and the world loads very slowly. 
> I hope Powernukkit haves a better codequality for it

Will those plug-in make my world suffer again?
