### ISSUE TITLE
Can't support the Minecraft Bedrock 1.17.10 version

### ISSUE THREAD

**Issue by xsy2004** [PowerNukkit/PowerNukkit#1215]
# 🤷‍♀️ I have a question

The latest version PowerNukkit v1.5.1.0-PN can't support the Apple IOS Minecraft Bedrock 1.17.10 version.

**Comment by MonoAdrian23** [comment]
The latest Version is 1.5.2.0
You can find these version in Teamcity

**Comment by Gabriel8579** [comment]
Download from here https://builds.powernukkit.org/buildConfiguration/PowerNukkit_Snapshots/466 make sure to download the `-shaded.jar` one
