### ISSUE TITLE
Raknet Problem Number 2

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1229]
# 🐞 I found a bug
 36m13:44:19[m [[m[1;31mERROR[m[m] An exception occurred in RakNet (Server)

io.netty.channel.unix.Errors$NativeIoException: sendToAddress(..) failed: Invalid argument

This Error spamms console and i dont know why.
Its Not reproducable by me.

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: git-cb4ac65
* Debug link: https://debugpaste.powernukkit.org/pastes/PNef89c564
* Timings link (if relevant): ✍

**Comment by joserobjr** [comment]
Closing as duplicated of #1056 please let's keep our effort to resolve this problem there
