### ISSUE TITLE
Blocklynukkit plugin bugs server

### ISSUE THREAD

**Issue by mercadanteus** [PowerNukkit/PowerNukkit#1241]
When you use the blockly nukkitx plugin nobody can join the server

### ▶ Steps to Reproduce
1. Download blockly nukitx at https://cloudburstmc.org/resources/blocklynukkit-%E2%80%94%E2%80%94-efficient-plugin-development-framework.416/
2. Put it on server's plugins folder
3. Restart server, and try to join

### ✔ Expected Behavior
join flawlessly

### ❌ Actual Behavior
nobody can join

### 📋 Debug information
DEBUG:  https://debugpaste.powernukkit.org/pastes/PN192a9952/
TIMINGS:  https://timings.aikar.co/?id=b9f85860d71b4121a8fd93419125f9cf
* PowerNukkit version: 1.5.2.0-PN-SNAPSHOT (git-74f000d) PowerNukkit (API 1.0.13)

### 💢 Crash Dump, Stack Trace and Other Files
No crash dump, this is the log:  https://debugpaste.powernukkit.org/pastes/taqenilile.yaml

**Comment by MonoAdrian23** [comment]
Please contact the Owner of BlocklyNukkit.
Because this error Happens in Nukkit too.

**Comment by mercadanteus** [comment]
> Please contact the Owner of BlocklyNukkit. Because this error Happens in Nukkit too.

I reposted this in Blocky Nukkit issues

**Comment by Mcayear** [comment]
This is a problem with BlocklyNukkit, the author is unable to update it due to academic problems.
Please download the community fix version: [https://vusv.cn/usr/uploads/2021/BlocklyNukkit(Compatible1.17.30).jar](https://vusv.cn/usr/uploads/2021/BlocklyNukkit(Compatible1.17.30).jar)

**Comment by PocketMiner92** [comment]
Its fixed

**Comment by Superice666** [comment]
I'm the author of BlocklyNukkit. Now it can works with powernukkit well, pls close this issue. thx

**Comment by PocketMiner92** [comment]
@mercadanteus
