### ISSUE TITLE
[Bug] Gamemode 3 fly

### ISSUE THREAD

**Issue by Bubbelwubbel** [PowerNukkit/PowerNukkit#1245]
# 🐞 I found a bug

### ▶ Steps to Reproduce
1. I have entered game mode 3
2. i flew up
3. and got kicked for Fly

### ✔ Expected Behavior
- That I can fly in game mode 3

### ❌ Actual Behavior
- I got kicked :C

📋 Debug information
- Nukkit 1.5.2.0-PN-SNAPSHOT (git-74f000d) | Version 1.0.13 | Bedrock v1.17.30 (465)

**Comment by LoboMetalurgico** [comment]
I couldn't reproduce. This issue still happens?

**Comment by PocketMiner92** [comment]
Yes
You must Leave a Server with Gm3
Then Join the Server and doublejump
