### ISSUE TITLE
Nether Biomes & Packets

### ISSUE THREAD

**Issue by justin-eckenweber** [PowerNukkit/PowerNukkit#1252]
# ❇ Feature Request

👉 Could you add the new Nether Biomes & Packets? (Not in the generator, just so that developers can use the biomes in custom Generators?). That would be awesome! Because I don't want to make a custom version of PowerNukkit.

**Comment by FlamingKnight** [comment]
If you want, this is all you need under the EnumBiome https://github.com/FlamingKnight/Nukkit/blob/pn-nether-generation/src/main/java/cn/nukkit/level/biome/EnumBiome.java#L105

**Comment by JustinLLDV** [comment]
Well that would help a lot. But I want it to be in the official PowerNukkit, because I don't like to maintain a custom version. But I think it's the only thing I can do, atm.
