### ISSUE TITLE
Cannot walk around chest while sneaking

### ISSUE THREAD

**Issue by PleaseInsertNameHere** [PowerNukkit/PowerNukkit#1255]
# 🐞 I found a bug

### ▶ Steps to Reproduce
1. Sneak
2. Walk around the edge of a chest

### ✔ Expected Behavior
You can walk around it

### ❌ Actual Behavior
You cannot walk around it

### 📋 Debug information

* PowerNukkit version: 1.5.1.0-PN✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by LoboMetalurgico** [comment]
Looks it's a vanilla bedrock feature. Closing as non-issue: vanilla behaviour.

If you believe this is an error, please reopen this issue providing more details.
