### ISSUE TITLE
EconomicAPI2.01

### ISSUE THREAD

**Issue by ReiyansCN** [PowerNukkit/PowerNukkit#1281]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Star pn server 
2. Run Plugin 'EconomyAPI2.01'
3. See error

**Comment by PocketMiner92** [comment]
Version 2.0.2 is latest and should work

**Comment by IWareQ** [comment]
Please send immediately a link to the bug (pastebin or hastebin), because if this is a plugin bug, then no one will fix it except the developer.  Also, no one will download this plugin now and check whether it works or not.

**Comment by Pluto999** [comment]
I had the same issue. Just use the version 2.0.2 https://cloudburstmc.org/resources/economyapi.14/version/2044/download

**Comment by PocketMiner92** [comment]
Use LlamaEconomy.
