### ISSUE TITLE
No Mob AI

### ISSUE THREAD

**Issue by Pluto999** [PowerNukkit/PowerNukkit#1282]
# 🐞 I found a bug
Mobs don't mot at version git-47e7289

### ✔ Expected Behavior
* movement 
### ❌ Actual Behavior
* no movement

### 📋 Debug information
* PowerNukkit version: git-47e7289

**Comment by PocketMiner92** [comment]
You can Use MobPlugin from Cloudburst

**Comment by PocketMiner92** [comment]
https://cloudburstmc.org/resources/mobplugin.3/

**Comment by Pluto999** [comment]
Thanks, that helped
