### ISSUE TITLE
Wheat, Carrots, Pumpin and more cant grow.

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkit/PowerNukkit#1297]
# 🐞 I found a bug
 In Powernukkit 1.6.0.0 B126 (Latest) from Teamcity nothing can grow.
You can wait 30 Minutes and nothing happens.

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: ✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by LoboMetalurgico** [comment]
Growing normally here. Are you using some plugin?

**Comment by PocketMiner92** [comment]
No, I have Tested it without plugins

**Comment by PocketMiner92** [comment]
In latest Powernukkit it works.
Hm weird

**Comment by Gabriel8579** [comment]
Closing as stale
