### ISSUE TITLE
Nametag Bug

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkit/PowerNukkit#1298]
# 🐞 I found a bug
 https://github.com/Nukkit-coders/MobPlugin/issues/252

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-70f88e5)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by roridev** [comment]
fixed at https://github.com/CloudburstMC/Nukkit/pull/1950

**Comment by roridev** [comment]
let me guess why this was closed? "unsupported software".
god forbid you don't work full time on an oss project nowdays.

**Comment by LoboMetalurgico** [comment]
Fixed in #1303

**Comment by PocketMiner92** [comment]
Thanks and sorry for my Idiot comments
