### ISSUE TITLE
Fishing Rod Loot

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkit/PowerNukkit#1300]
# 🐞 I found a bug
 Try to Catch a fish with an Fishing Rod. It works great but the Loot Lands behind a Player and not in Inventory

### ▶ Steps to Reproduce

1. Use Fishing Rod
2. Catch a Fish
3. Now you can See, the fish or whatever lands behind the Player and not directly in Inventory

### 📋 Debug information

* PowerNukkit version: (git-70f88e5)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by roridev** [comment]
uh.

**Comment by PocketMiner92** [comment]
This behaviour is normal If a Player Stands Higher then sea. This issue is invalid.
