### ISSUE TITLE
Doublechest Inventory Bug

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkit/PowerNukkit#1301]
# 🐞 I found a bug
 Many Items are Missing in Doublechests If this placed in two different Chunks or Missing ChestPaired. I havent found any Files for for Doublechest or another.
I Break the Chest and all Items are Available.
This is a very important Issue.
@LoboMetalurgico @joserobjr 

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-70f88e5)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by roridev** [comment]
Related to: #1053

**Comment by PocketMiner92** [comment]
Why you have tagged the Comperator PR?
This Issue haves nothing to die anything with Comperators.
This Issue with Doublechests is existing since 1.3.5.0
This is a Chunk Problem.
Its much more useful to fix and not add useless Tags

**Comment by roridev** [comment]
Look, the issue is the same. Its an *old* bug. This is all the issues that are related to it.

**Comment by PocketMiner92** [comment]
The Double Chest doenst Unlink.
The Double Chest is a Double Chest but you cant See the Inventory of this Double Chest.
You must Break the Chest to get all all Items in this doublechest.

Jesuuuuus!
There is nothing to Mention.
I give Up and i dont know whats youre Job is in Powernukkit.

**Comment by roridev** [comment]
Can you read #1053?
I have placed a Doublechest and have filled this with cobblestone.


After a while, this chest is empty.
**The Double Chest is a Double Chest but you cant See the Inventory of this Double Chest.**

But after I have tried to break this chest, all chest Inventory was dropped.
**You must Break the Chest to get all all Items in this doublechest.**

I think, this is a problem when a Doublechest is placed in two different chunks.
**This is a Chunk Problem.**

This is to me the exact same issue.
