### ISSUE TITLE
Damage Bug while wearing Elytra

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkit/PowerNukkit#1304]
# 🐞 I found a bug
 If you wear a Elytra, you can glide througt Blocks and you get damage.
If you are flying fast, you Bug Back to Last Position.
I think the gliding isnt correct.
I have Testing IT with a Cape and Elytra at Same time.

### 📸 Screenshots / Videos
 
![Screenshot_20220201-092114~2](https://user-images.githubusercontent.com/96331694/151935064-285b898e-e7fb-488d-8d4e-e0943724ca28.png)

### ▶ Steps to Reproduce

1. Build a Place Like my Example Picture
2. Wear a Elytra
3. Try to Walk in this hole
4. You can, and you get damage.

### 📋 Debug information

* PowerNukkit version: (git-70f88e5)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by PocketMiner92** [comment]
I close it because Powernukkit is dead

**Comment by Gabriel8579** [comment]
I couldn't reproduce, can you record a video showing it?

Here it's how I tested it: https://youtu.be/ftiJ3GLsQS4

**Comment by PocketMiner92** [comment]
It was a Bug with custom skin.
Its resolved

**Comment by Gabriel8579** [comment]
Thank you
