### ISSUE TITLE
New 384-height world in 1.18

### ISSUE THREAD

**Issue by Superice666** [PowerNukkit/PowerNukkit#1308]
# ❇ Feature Request
Expand the current 256-height anvil world into a 384-height world.

### 💬 Anything else we should know?
I think there's 3 things to do:
1. Change the field `vanillaVersion` into `1.18.0`
2. Protocol support 1.18.0 new LevelChunkPacket (Append four empty chunk section in the packet)
3. Update our anvil format to fully support 384-height world.

Currently, I'm working on my [`patch/384-world`](https://github.com/BlocklyNukkit/PowerNukkitX/tree/patch/384-world) fork but encountered some problems. I have already finished step 1 and working on step 2. I noticed that now minecraft use a 3D biome instead the old 2D biome. I'm trying to 3Dify our 2D biomes and send in the packet. Unfortunately, the client stop responce when I trying to join the world. Is there anyone who can help? thx.

Here is the code I edited int Anvil.java
```java
    @Override
    public AsyncTask requestChunkTask(int x, int z) throws ChunkException {
        Chunk chunk = (Chunk) this.getChunk(x, z, false);
        if (chunk == null) {
            throw new ChunkException("Invalid Chunk Set");
        }

        long timestamp = chunk.getChanges();

        byte[] blockEntities = EmptyArrays.EMPTY_BYTES;

        if (!chunk.getBlockEntities().isEmpty()) {
            List<CompoundTag> tagList = new ArrayList<>();

            for (BlockEntity blockEntity : chunk.getBlockEntities().values()) {
                if (blockEntity instanceof BlockEntitySpawnable) {
                    tagList.add(((BlockEntitySpawnable) blockEntity).getSpawnCompound());
                }
            }

            try {
                blockEntities = NBTIO.write(tagList, ByteOrder.LITTLE_ENDIAN, true);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }

        BinaryStream stream = ThreadCache.binaryStream.get().reset();
        int count = 0;
        cn.nukkit.level.format.ChunkSection[] sections = chunk.getSections();
        for (int i = sections.length - 1; i >= 0; i--) {
            if (!sections[i].isEmpty()) {
                count = i + 1;
                break;
            }
        }
        for (int i = 0; i < count; i++) {
            sections[i].writeTo(stream);
        }
        // TODO: maybe wrong here
        final byte[] biomeData = serializeBiome(chunk);
        for (int i = 0; i < 25; i++) {
            stream.put(biomeData);
        }
        stream.putByte((byte) 0); // Border blocks - Edu edition only
        stream.putUnsignedVarInt(0); // extra data length, 0 for now
        stream.put(blockEntities);

        this.getLevel().chunkRequestCallback(timestamp, x, z, count, stream.getBuffer());

        return null;
    }

    private byte[] serializeBiome(Chunk chunk) {
        final BinaryStream stream = new BinaryStream(new byte[4096]);
        final PalettedBlockStorage blockStorage = new PalettedBlockStorage();
        for (int x = 0; x < 16; x++) {
            for (int z = 0; z < 16; z++) {
                for (int y = 0; y < 16; y++) {
                    blockStorage.setBlock((x << 8) | (z << 4) | y, chunk.getBiomeId(x, z));
                }
            }
        }
        blockStorage.writeTo(stream);
        final byte[] buffer = stream.getBuffer();
        return buffer;
    }
```

### Useful Information
https://github.com/GeyserMC/Geyser/blob/a39de7d7d245b4bef3b845452dfcc00e9999232d/core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaLevelChunkWithLightTranslator.java
https://github.com/GeyserMC/Geyser/blob/a39de7d7d245b4bef3b845452dfcc00e9999232d/core/src/main/java/org/geysermc/geyser/translator/level/BiomeTranslator.java#L90
https://github.com/pmmp/PocketMine-MP/blob/59de045ecbacfb9acc297e75170819727d68ae09/src/network/mcpe/serializer/ChunkSerializer.php#L65
https://github.com/Sandertv/gophertunnel/blob/6c60fe77ccb5b0a2f77bba97a815e50f7f0bc53f/minecraft/protocol/packet/level_chunk.go

**Comment by PocketMiner92** [comment]
Without LevelDB Support, this Change IS very laggy.
I have try it and it was succesfull.
But it lags to much.
And without new ores and Other Stuff, this Change is useless.

**Comment by Superice666** [comment]
Fixed in [patch/384-world](https://github.com/BlocklyNukkit/PowerNukkitX/tree/patch/384-world), close.

**Comment by roridev** [comment]
patch/384 is in a fork, its not implemented on main powernukkit, reoprning this feature request.
