### ISSUE TITLE
1.18.10 Compatability - Latest Update Throws Outdated Server.

### ISSUE THREAD

**Issue by azura4k** [PowerNukkit/PowerNukkit#1313]
# 🔌 Plugin compatibility issue

It seems as though Mojang pushed a bug fix out today, that most likely updated protocol. Sadness, but this is just how it be.

**Comment by azura4k** [comment]
> Hey @azura4k, thank you for the report!
> 
> ⚠️ **I could not find which PowerNukkit version you are using from your message.** ⚠️
> 
> Please, run the command: `/debugpaste` (legacy) or `/debugpaste upload` (1.4.0.0-PN+) it will generate a link, send us this link replying this issue. It's an important step to get your issue resolved.
> 
> Don't say _latest_ or _current version_, we support different versions and your latest may not be the same latest as our, and your latest will not be the same latest in the future, so please, use a fixed version.
> 
> Thank you 👍

https://debugpaste.powernukkit.org/pastes/PNf2f6a5da

**Comment by 9had** [comment]
I have the same issue. 
https://debugpaste.powernukkit.org/pastes/PN1cb8b7d8

**Comment by PocketMiner92** [comment]
Devs are working on this Update.
Be Patient.

**Comment by azura4k** [comment]
> Why was this Issue Closed?
> It isnt resolved!

This issue is resolved, in discord, 1.18.10 is technically supported by beta now, there's just other issues being checked out before it's production server level

**Comment by PocketMiner92** [comment]
I Hope you know that this Update is Experimental.
And Not everyone use Discord.

**Comment by 9had** [comment]
> 

And where do I get the beta? I do not see any new snapshots on the "bleeding edge"...

**Comment by azura4k** [comment]
> I Hope you know that this Update is Experimental.
> And Not everyone use Discord.
> 

I'm aware, and fair point. I'll reopen the issue then.

**Comment by azura4k** [comment]
> > 
> 
> 
> 
> And where do I get the beta? I do not see any new snapshots on the "bleeding edge"... 

I'm mistaken, they are not on package level. If you wanted to use it, you would have to compile it yourself. My apologies.

**Comment by 9had** [comment]
I am trying to compile it right now, but last few times i tried to do that, my Raspberry Pi wasn't able to do the job. :) So I opted to bleeding edge. Not sure if it was some kind of dependency or if I needed some extra software to be able to compile .jar files.

**Comment by azura4k** [comment]
> I am trying to compile it right now, but last few times i tried to do that, my Raspberry Pi wasn't able to do the job. :) So I opted to bleeding edge. Not sure if it was some kind of dependency or if I needed some extra software to be able to compile .jar files. 
> 
> 

Ahh, now that I'm not sure how to help you. I'm just a server owner so I never got into the bleeding edge or compiling from source too much. My only recommendation is if it's for a production server, to wait for official release.

**Comment by 9had** [comment]
It's just local server for my son and I. But we got our Minecraft iOS apps updated, and server is now "outdated". So bleeding is fine, I think.

**Comment by azura4k** [comment]
> It's just local server for my son and I. But we got our Minecraft iOS apps updated, and server is now "outdated". So bleeding is fine, I think. 

Well the most pressing issue that's stopping full release is a spree of nether glitches in spawning and block placement. So if you plan on going to the nether, may just wanna wait a tad bit longer.

**Comment by PocketMiner92** [comment]
Nether is Not usable.
You should Pin this Issues Here.

**Comment by PocketMiner92** [comment]
frog_spawn 723:0
pearlescent_froglight 724:0
verdant_froglight 725:0
ochre_froglight 726:0

**Comment by alikindsys** [comment]
We support this protocol version since #1314, and it is available as a [stable release](https://powernukkit.org/#stable) since `1.6.0.0-PN`. 
Closing the issue
