### ISSUE TITLE
Placing Blocks/Nether

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkit/PowerNukkit#1315]
# 🐞 I found a bug
 Try to place any Block in Nether Dimension, all Blocks are changing to Netherrack.

### ▶ Steps to Reproduce

1. Place any Block in Nether
2. It Changes to Netherrack
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: git-37b1ff9
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by Gabriel8579** [comment]
Fixed in b64c0512a03c0453b97a366056218a93d72bb78d keeping this issue open
