### ISSUE TITLE
Broken IDS in Nether World

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkit/PowerNukkit#1316]
# 🐞 I found a bug
 31mERROR[m[m] Found an unknown BlockId:Meta combination: 144:0 - minecraft:skull;facing_direction=0;no_drop_bit=0 - BlockProperties{bitSize=4, properties=[0-3:facing_direction, 3-4:no_drop_bit]} - minecraft:skull, trying to repair or replacing with an "UPDATE!" block.
144:1
144:2
144:3
144:4
144:5

### ▶ Steps to Reproduce

1. Go to Nether world
2. The Error at Top is appear
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: git-37b1ff9
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by Gabriel8579** [comment]
#1317 may be the source of the issue

**Comment by PocketMiner92** [comment]
It comes only in Nether World

**Comment by PocketMiner92** [comment]
Do you know what it is?

**Comment by Gabriel8579** [comment]
I don't know yet, that comment about the possible cause was supposed to be in another issue

**Comment by Gabriel8579** [comment]
mojang removed the no_drop_bit property, this was just a warning that PowerNukkit gave, informing that it will also remove this property from the existing block

**Comment by PocketMiner92** [comment]
But this IDS are weird.
Me says
397:0 Skeleton Head
397:1 Wither Skeleton Head
397:2 Zombie Head
397:3 Mobhead (Steve)
397:4 Zombie Head
397:5 Dragonhead
