### ISSUE TITLE
Nether Generator is broken

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkit/PowerNukkit#1317]
# 🐞 I found a bug
 Nether Generation is complety broken.

### 📸 Screenshots / Videos
 

![Screenshot_20220211-074758_Minecraft.jpg](https://user-images.githubusercontent.com/96331694/153548535-21adbab7-b5c6-4e26-a29d-cc122eb83243.jpg)

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: git-37b1ff9
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by Gabriel8579** [comment]
Fixed in b64c0512a03c0453b97a366056218a93d72bb78d

**Comment by PocketMiner92** [comment]
It workes great
Thank you very much Gabriel
