### ISSUE TITLE
Smithing Table doenst work

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkit/PowerNukkit#1320]
# 🐞 I found a bug
 You can place a Tool and a Netherite Ingot in Smithing Table but it doenst show the result.

### ▶ Steps to Reproduce

1. Place a Smithing Table
2. Try to create a Netherite Tool
3. You can put all in but there is no Result

### 📋 Debug information

* PowerNukkit version: git-b64c051
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by Gabriel8579** [comment]
Fixed at 0bdd3abdae3dc6bbe0e598bb71b1c0480ed0017c
