### ISSUE TITLE
netherite not working

### ISSUE THREAD

**Issue by BrunoJaegerK** [PowerNukkit/PowerNukkit#1322]
When using the netherite ingots they do not work they are obsolete.
![IMG-20220211-WA0027](https://user-images.githubusercontent.com/99422811/153721271-136ccf24-c608-4cb7-8abf-21a30acb2722.jpeg)
Started from new update previously if they worked

**Comment by BrunoJaegerK** [comment]
https://debugpaste.powernukkit.org/pastes/PNa7d3b31a/

**Comment by Gabriel8579** [comment]
Closing as duplicated
