### ISSUE TITLE
White Dye = Bonemeal in Creative

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkit/PowerNukkit#1346]
# 🐞 I found a bug
 White Dye is called Bonemeal in Creative

### 📸 Screenshots / Videos

![Screenshot_20220421-122648_Minecraft.jpg](https://user-images.githubusercontent.com/96331694/164441251-30c10039-9c11-4062-81d3-ddffab9e3362.jpg)

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-c17e2a7)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by Polyana-Fontes** [comment]
This is a vanilla client bug that we can't fix in our end: https://bugs.mojang.com/browse/MCPE-153522

They should fix it in an internationalization patch that may or may not require a client update.
