### ISSUE TITLE
Players swim through blocks

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkit/PowerNukkit#1353]
# 🐞 I found a bug
 Players can swim through blocks
See picture.

### 📸 Screenshots / Videos

![20220508_165128.jpg](https://user-images.githubusercontent.com/96331694/167301959-49f8b7bd-be70-4b92-845a-3e756cba8ded.jpg)

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-c17e2a7)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by IWareQ** [comment]
Nothing is clear here.

Please use vanilla textures and record a video so that everything is clear.

Thanks for understanding.

**Comment by PocketMiner92** [comment]
Whats Not clear Here?
You can See a Player under Water.
This Player can swim 1 Block because the Hitbox is Not correct.
You can Test it by yourself with Vanilla Textures or let IT be.
This Picture say all

**Comment by IWareQ** [comment]
This picture says nothing, I see here only blocks and a nickname under the blocks, I don’t see here that a person is swimming under the blocks or in them

**Comment by PocketMiner92** [comment]
Test it self and dont waste my time.

**Comment by PleaseInsertNameHere** [comment]
can reproduce

**Comment by PleaseInsertNameHere** [comment]
Happening since commit `c1f21c34c5527a754c90d228c07c2bd6797e8b0b` (PR #576)

**Comment by TobidieTopfpflanze** [comment]
Just to clarify this issue. 

Does the player cliping in blocks or is the player just able to swim through 1x1 Blocks, like the picture below?
![image](https://user-images.githubusercontent.com/39420707/167458723-6fb13616-491a-427c-b25a-c780ced2542b.png)

The third option would be this case that the player is able to walk in a 1x1 block after swimming?
![image](https://user-images.githubusercontent.com/39420707/167459017-2dfc368a-0de1-40c1-ab66-683414e1f279.png)

Please tell me which of these 3 cases you are experiencing.

**Comment by TobidieTopfpflanze** [comment]
Also let me know, if none of the cases above are matching your behavior.

**Comment by PocketMiner92** [comment]
I think the First one is correct.
I have asked all Players He can See Other Blocks while this.
But no.
Its only 1x1

**Comment by alikindsys** [comment]
Swimming thru a 1x1 hole is vanilla behavior. Closed. 

https://user-images.githubusercontent.com/36565196/175989523-eeba1252-f778-49c2-ab47-cfd6bdd50bb8.mp4
