### ISSUE TITLE
Server Crash 04:36 (German Time) everyday

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1358]
# 🐞 I found a bug

![Screenshot_20220521-082754_Log Viewer.jpg](https://user-images.githubusercontent.com/59027482/169639065-b50e9188-4f2a-4f14-99da-9fd8f8d6f10c.jpg)

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-c17e2a7)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
@LoboMetalurgico 
@joserobjr 
@roridev

**Comment by hteppl** [comment]
Please upload thread trace on pastebin, there can be information about server stopping.

**Comment by MonoAdrian23** [comment]
https://file.io/Uk0vBTpiflF9

**Comment by MonoAdrian23** [comment]
@hteppl

**Comment by LoboMetalurgico** [comment]
> https://file.io/Uk0vBTpiflF9

Deleted file :/

**Comment by MonoAdrian23** [comment]
https://file.io/Lb7TQK4KiPit

**Comment by MonoAdrian23** [comment]
@LoboMetalurgico
