### ISSUE TITLE
Red Mushroom Block not dropping mushroom item

### ISSUE THREAD

**Issue by SamuelLimaCap** [PowerNukkit/PowerNukkit#1371]
# 🐞 I found a bug
👉 Red mushroom block is not dropping any mushroom item.

### 📸 Screenshots / Videos
https://www.youtube.com/watch?v=4XZueoXn6FM

### ▶ Steps to Reproduce

1. Get RED_MUSHROOMS_BLOCK (ID 100 on PowerNukkit)
2. Place them on the ground
3. Break all mushrooms block

### ✔ Expected Behavior
Expected to give at least 1 mushroom breaking 10 or 20 blocks.

### ❌ Actual Behavior
You break 20 blocks and get nothing.

### 📋 Debug information

* PowerNukkit version: ✍bleeding branch, after commit c9f67c981c4f3c3a8957bb90edc6e21102aa912a

### 💬 Anything else we should know?
I'm making some tests and maybe this should be the problem:
![image](https://user-images.githubusercontent.com/67354841/177234332-7511d5ac-ad16-4fbe-b31a-5218ef698798.png)

**Comment by LoboMetalurgico** [comment]
Fixed in #1379
