### ISSUE TITLE
add raw ore

### ISSUE THREAD

**Issue by feanchy** [PowerNukkit/PowerNukkit#1374]
# ❇ Feature Request

### 📸 Screenshots / Videos
[<!-- ✍ (https://youtu.be/LfSvJFUYhwM)

### ✔ Expected Behavior
<!-- ✍ instead of iron, copper, gold ore, the unprocessed ore that I listed should fall out

### ❌ Actual Behavior
<!-- ✍ ordinary ore fell out :/

**Comment by alikindsys** [comment]
Duplicate of #1373
