### ISSUE TITLE
[2.0] Can't replace tallgrass when placing a redstone wire

### ISSUE THREAD

**Issue by joserobjr** [PowerNukkit/PowerNukkit#167]
### Expected Behavior
Replace the tallgrass with a redstone wire

### Actual Behavior

The redstone wire replaces for a fraction of a seconds then it rollsback

### Steps to Reproduce

1. Find a tallgrass
2. Get a redstone dust
3. Click the tallgrass while holding the redstone dust

### Debug information
v2.0

**Comment by Gabriel8579** [comment]
Same happens in master branch

**Comment by Plugner** [comment]
Fixed in pull request ( #556 ). (First replace to AIR then, replace to redstone wire.)
