### ISSUE TITLE
Redstone dust doesn't replace tallgrass properly

### ISSUE THREAD

**Issue by Gabriel8579** [PowerNukkit/PowerNukkit#282]
# 🐞 I found a bug

### 📸 Screenshots / Videos

https://youtu.be/5uD8wIxzaKg
https://youtu.be/H0cooxUaGKs

### ▶ Steps to Reproduce

1. Find a tallgrass
2. Get a redstone dust
3. Click the tallgrass while holding the redstone dust

### ✔ Expected Behavior

Redstone replaces the tallgrass completely

### ❌ Actual Behavior

Redstone does not replace tallgrass properly

### 📋 Debug information

* PowerNukkit version: 1.2.1.0-PN-SNAPSHOT
* Debug link: https://hastebin.com/iqimulaqag

**Comment by Plugner** [comment]
Already fixed in pull request ( #556 )
