### ISSUE TITLE
Nether Portal

### ISSUE THREAD

**Issue by Jl1mbo** [PowerNukkit/PowerNukkit#289]
# 🐞 I found a bug
When creating a portal in Nether at any coordinates, for example, 100, 50, 100, a portal in Nether always creates at 0, 69, 0 coordinates, and when I teleport back, I teleport to 0, 0, 0 and the new portal is saved, and  not the one I teleported to

### 📸 Screenshots / Videos
https://youtu.be/uM30UiBuJA0

### ▶ Steps to Reproduce
1. Build a portal on any coordinates
2. Go into it
3. Go back in it
4. Will appear elsewhere

### ✔ Expected Behavior
The portal in Nether will be created on the same coordinates as in the ordinary world, and when teleporting, it will teleport to the same portal, and will not create a new one

### ❌ Actual Behavior
The portal was created on random coordinates and, when teleported, was created elsewhere and did not return to the same

### 📋 Debug information
* PowerNukkit version: latest version

**Comment by joserobjr** [comment]
Thank you for the report

**Comment by joserobjr** [comment]
I think this will be an important fix for the nether update

**Comment by tuilakhanh** [comment]
Nether doesn't work on non-default worlds. 

Log: https://hastebin.com/hezigavaya.css

**Comment by Jl1mbo** [comment]
> Nether doesn't work on non-default worlds.
> 
> Log: https://hastebin.com/hezigavaya.css

It should be so

**Comment by Jl1mbo** [comment]
Well?

**Comment by joserobjr** [comment]
Linking related issues:
#36
CloudburstMC#660

**Comment by MrRazamataz** [comment]
So will this fix the linkup issue?
