### ISSUE TITLE
Change Gamemode Message Shows %s

### ISSUE THREAD

**Issue by LoboMetalurgico** [PowerNukkit/PowerNukkit#298]
# 🐞 I found a bug
When you change the user's game mode using the server console (idk if this also occurs on the game console), the message shows %s instead of the gamemode.

### 📸 Screenshots / Videos
![image](https://user-images.githubusercontent.com/3679022/86054739-0e0b3200-ba31-11ea-83aa-62ded7effc32.png)

### ▶ Steps to Reproduce
1. Run command 'gamemode survival/creative/spectator username' on Server Console
2. See the %s in the message

### ✔ Expected Behavior
Show the target gamemode (survival/spectator/creative/adventure)

### ❌ Actual Behavior
Show %s instead the gamemode

**Comment by joserobjr** [comment]
Fixed with #445 (or a later commit related to this PR)
