### ISSUE TITLE
Potential compatibility issue with FakeInventories

### ISSUE THREAD

**Issue by joserobjr** [PowerNukkit/PowerNukkit#321]
# 🔌 Plugin compatibility issue

A compatibility issue with FakeInventories has been reported by @MrRazamataz in https://github.com/GameModsBR/PowerNukkit/issues/295#issuecomment-650838852_

### 📸 Screenshots / Videos

Not Informed

### ▶ Steps to Reproduce

Not Informed

### ✔ Expected Behavior

Not Informed

### ❌ Actual Behavior

Not Informed

### 📋 Debug information

* PowerNukkit version: 1.3.0.0-PN-SNAPSHOT
* Debug link: https://hastebin.com/vubizotena
* Timings link (if relevant):  https://timings.aikar.co/?id=59339f5287f24911a861471c5f8a3450

### 💢 Crash Dump, Stack Trace and Other Files

Not informed

### 💬 Anything else we should know?

https://ci.nukkitx.com/job/NukkitX/job/FakeInventories/job/master/

**Comment by Htepple** [comment]
Has something changed? FakeInventories not working :c

**Comment by Jl1mbo** [comment]
> Has something changed? FakeInventories not working :c

Yes

**Comment by Htepple** [comment]
> > Has something changed? FakeInventories not working :c
> 
> Yes

After issue created, i mean..

**Comment by MrClean1337** [comment]
Its working 50% with crashes.

See https://github.com/PowerNukkit/PowerNukkit/issues/365#issuecomment-659066818

**Comment by joserobjr** [comment]
Closing because it was reported by the community that FakeInventories is working with 1.3.1.2-PN and there are no known compatibility issues with it right now
