### ISSUE TITLE
Bamboo wrong behaviors 

### ISSUE THREAD

**Issue by Gabriel8579** [PowerNukkit/PowerNukkit#360]
# 🐞 I found a bug

PowerNukkit (1.3.0.1)

### ✔ Expected Behavior
Can grow bamboo by using bone meal on any bamboo part;
Can grow bamboo by using another bamboo on any bamboo part;
Effective tool is a Sword;
Hardness is 1;
Can harverst with hand;

### ❌ Actual Behavior
Can grow bamboo by using bone meal only on bamboo top part;
Can't grow bamboo by using another bamboo;
Effective tool is a Pickaxe;
Hardness is 2;
Can't harverst with hand (I still haven't figured out the reason);
Wrong break time.

**Comment by joserobjr** [comment]
Worth mentioning that the bamboo bounding box is wrong and may cause kicks for flying because I couldn't find how the client decides the actual XZ position that the bamboo will grow #69

**Comment by Gabriel8579** [comment]
Testing again, it is possible to break the bamboo by hand, but the breaking time is incorrect

**Comment by Gabriel8579** [comment]
Vanilla:
Bamboo can grow to layer 255 (maximum altitude of blocks)

PowerNukkit:
Can grow bamboo in up to 15 layers

**Comment by Gabriel8579** [comment]
Testing I noticed that the hardness is really 2 in the vanilla
