### ISSUE TITLE
Kelp can grow infinity with bone meal (without using bonemeal)

### ISSUE THREAD

**Issue by good777LUCKY** [PowerNukkit/PowerNukkit#362]
# 🐞 I found a bug

Kelp can grow infinity with bone meal (without using bonemeal).

### 📸 Screenshots / Videos

(I don't have video.)

### ▶ Steps to Reproduce

1. Use bonemeal to kelp
2. Kelp will grow but bonemeal doesn't reduce even the player is survival gamemode.

### ✔ Expected Behavior

Bonemeal will reduce.

### ❌ Actual Behavior

Not reduce.

### 📋 Debug information

* PowerNukkit version: 1.3.1.0
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

No crash

### 💬 Anything else we should know?

Similar issue with #360

**Comment by joserobjr** [comment]
Thank you, it's fixed in the bleeding branch
