### ISSUE TITLE
Firedamage gamerule false doesnt stop fire from breaking blocks

### ISSUE THREAD

**Issue by MrRazamataz** [PowerNukkit/PowerNukkit#363]
### 📸 Screenshots / Videos
https://www.youtube.com/watch?v=NI6Al8KfBDc

### ✔ Expected Behavior
Block doesnt burn but doesnt get destroyed.

### ❌ Actual Behavior
Block burns and gets destroyed.

### 📋 Debug information
This server is running Nukkit 1.4.0.0-PN-SNAPSHOT (git-5b8919e) 「PowerNukkit」 implementing API version 1.0.11 for Minecraft: BE v1.16.0 (protocol version 407)

**Comment by good777LUCKY** [comment]
fireDamage gamerule prevent player burning not for blocks. Block is doFireTick.

**Comment by MrRazamataz** [comment]
Isnt block tick to say if the fire stops burning or not?

**Comment by good777LUCKY** [comment]
doFireTick false will stop spreading fire and make not fire destroy blocks. Also it will not disappear until you break fire.

**Comment by MrRazamataz** [comment]
Nope. I'm an idiot. Thanks for pointing that out!

**Comment by joserobjr** [comment]
You are not an idiot lol. That can really confuse anyone.

Thank you for reporting and also recording a video to show it, if it was a real issue that would have helped to spot and fix it.
