### ISSUE TITLE
Client is crashing using Fakeinventories with the latest PowerNukkit version. 

### ISSUE THREAD

**Issue by robertdudaa** [PowerNukkit/PowerNukkit#365]
# 🔌 Plugin compatibility issue

### ▶ Steps to Reproduce

1. Open a fakeinventory / add window
2. Close it in your code using `fakeInventory.close(player);`
3. Client is crashing
4. No error 

### ✔ Expected Behavior
Not crashing

### ❌ Actual Behavior
Client is crashing

### 📋 Debug information

* PowerNukkit version: 1.0.11 for 1.16

### 💬 Anything else we should know?
**Works absolutely fine using normal Nukkit 1.16.**

**Comment by PocketMiner82** [comment]
this isn't a compatibility issue, because the crash also happens when closing, for example a normal chest inventory (open a chest and let it destroy from another player, then you will crash)

**Comment by joserobjr** [comment]
Possible relation to #339

**Comment by MrClean1337** [comment]
Happens when server forces to close any kind of container.
If the player closes itself, nothing will happen :D

**Comment by PocketMiner82** [comment]
Something wrong with https://github.com/PowerNukkit/PowerNukkit/blob/master/src/main/java/cn/nukkit/network/protocol/ContainerClosePacket.java, i think

**Comment by PocketMiner82** [comment]
Is this really correct, casting it to byte?
https://github.com/PowerNukkit/PowerNukkit/blob/master/src/main/java/cn/nukkit/network/protocol/ContainerClosePacket.java#L22

**Comment by MrClean1337** [comment]
Yes must be

**Comment by joserobjr** [comment]
There are some new inventory fixes from NukkitX that was not pushed yet, maybe they solve this issue

**Comment by MrClean1337** [comment]
You mean https://github.com/CloudburstMC/Nukkit/commits/feature/1.16 ?

No they did not fix anything of that problem here. Even not that, what i reported https://discordapp.com/channels/393465748535640064/395586321252352010/732020971153653841

**Comment by joserobjr** [comment]
@MrClean1337 I mean that changes: https://github.com/CloudburstMC/Nukkit/compare/647b8cdc5cf5b852056f64a2fbe6e900a29540b4..6a43a0e74483d34aa2e4b526330cd7262cd3b88b

The features/1.16 got merged into the master there.

The changes change the position to [an inventory close method call](https://github.com/CloudburstMC/Nukkit/compare/647b8cdc5cf5b852056f64a2fbe6e900a29540b4..6a43a0e74483d34aa2e4b526330cd7262cd3b88b#diff-f64a11f301feaf1e99febeadf5414940L83). Maybe that was causing the client to crash.

**Comment by PocketMiner82** [comment]
This also fixed the cursor sending, that I wanted to fix with #349.  @joserobjr should I close the PR?

**Comment by MrClean1337** [comment]
@PocketMiner82 Its not really fixed, I tested it with fakeinvs https://discordapp.com/channels/393465748535640064/395586321252352010/732020971153653841

**Comment by PocketMiner82** [comment]
https://github.com/CloudburstMC/Nukkit/commit/3529299dd9cc21f6616794d8c6431457b5bcdde7

**Comment by MrClean1337** [comment]
As I told. Not really fixed

**Comment by PocketMiner82** [comment]
I see

**Comment by joserobjr** [comment]
> PowerNukkit version: 1.0.11 for 1.16 

@robertdudaa
Can you share the output of `/about` and the version of the FakeInventory plugin that you are using?
`1.0.11` is the Nukkit API version and not the PowerNukkit implementation. The version always have this syntax: `X.X.X.X-PN-(OPT-LABEL)`

**Comment by MrClean1337** [comment]
There is a fix for that, wait while im searching for it

**Comment by MrClean1337** [comment]
This dude https://discordapp.com/channels/393465748535640064/395586321252352010/731142894630600744
wrote to me that he fixed "crash causing by ContainerClosePacket" in pmmp

Its this, but for pmmp https://github.com/Muqsit/InvCrashFix/blob/master/src/muqsit/invcrashfix/Loader.php
They had the same issue. And nukkit is just a recode of pmmp, so it should work the same way in nukkit i think lul

**Comment by robertdudaa** [comment]
this issue seems urgent tbh.

**Comment by joserobjr** [comment]
Tracking: https://github.com/CloudburstMC/Nukkit/issues/1541

**Comment by joserobjr** [comment]
It's patched with a hotfix in 1.3.1.2-PN, users have reported that this issue does not happen anymore after the patch was applied.

Thank you all
