### ISSUE TITLE
Most of Crafting is broken on 1.4.0.0-PN-SNAPSHOT

### ISSUE THREAD

**Issue by good777LUCKY** [PowerNukkit/PowerNukkit#379]
# 🐞 I found a bug

Lot of crafting is broken.

### 📸 Screenshots / Videos

(Sorry I don't have video.)

### ▶ Steps to Reproduce

1. Craft Something (it will be on your inventory)
2. Hold that crafted thing
3. Disappeared.

### ✔ Expected Behavior

It will not disappear when you hold or move item that you craft.

### ❌ Actual Behavior

It disappeared.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT (f0add31) (git-8773e1b)
* Debug link: https://hastebin.com/bajixulagu
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

https://hastebin.com/sesujejiju

### 💬 Anything else we should know?

Every debug log start with `[main] DEBUG - Got unexpected normal inventory action with incomplete crafting transaction from {player name}, refusing to execute crafting`.

**Comment by joserobjr** [comment]
Which recipe did you make that caused this issue?

**Comment by good777LUCKY** [comment]
> Which recipe did you make that caused this issue?
> 
> NVM, iron_pickaxe, I've reproduced it here. Thank you for reporting.

I think every tools and armors can't be crafted. Also iron block, signs, etc.
Weird thing is log to planks are able to craft.
