### ISSUE TITLE
Discord is down, and GitHub Actions are failing

### ISSUE THREAD

**Issue by joserobjr** [PowerNukkit/PowerNukkit#381]
# 💬 Let's talk

Looks like an important global service is down and that made [our discord](http://powernukkit.org/discord) go offline.

The GitHub builds are also failing because it can't download the JDK.
![image](https://user-images.githubusercontent.com/3679022/87832367-3a5de580-c85c-11ea-9990-c82f0716b2f7.png)

Some game servers like Valorant seems to be down as well.

Due to this communication issue, I want to bring your attention that our website now has a discussion board at https://discuss.powernukkit.org .

![image](https://user-images.githubusercontent.com/3679022/87832584-af311f80-c85c-11ea-9583-bc623d5260cd.png)

Feel free to create new threads there if you want to communicate.

We can also use this issue as well.

**Comment by joserobjr** [comment]
![image](https://user-images.githubusercontent.com/3679022/87833000-9ffea180-c85d-11ea-8105-57e13d5b77cb.png)
https://twitter.com/discord/status/1284236135305113601

**Comment by Gabriel8579** [comment]
It was a problem with CloudFlare, it seems that everything has normalized...

**Comment by joserobjr** [comment]
Just a test, please ignore.
