### ISSUE TITLE
Doors can't be paired after crimson/warped door update (1.4.0.0-PN-SNAPSHOT)

### ISSUE THREAD

**Issue by good777LUCKY** [PowerNukkit/PowerNukkit#387]
# 🐞 I found a bug

Doors can't be paired after crimson/warped door update (1.4.0.0-PN-SNAPSHOT)

### 📸 Screenshots / Videos

Image A:
![Screenshot_20200719-134616_Minecraft](https://user-images.githubusercontent.com/43497313/87867358-0ce17b00-c9c7-11ea-89d3-0735a49b2c90.jpg)

Image B:
![Screenshot_20200719-134931_Minecraft](https://user-images.githubusercontent.com/43497313/87867361-12d75c00-c9c7-11ea-832a-f8e061aa1fba.jpg)

### ▶ Steps to Reproduce

1. Place a door.
2. Place another door at right of the door.
3. Door direction is not same as vanilla. (Image A)

### ✔ Expected Behavior

When you do 3, it will chamge direction like above image B.

### ❌ Actual Behavior

But it is like above image A.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

No crash.

### 💬 Anything else we should know?

- Latest bleeding branch.
- All doors have this problem but Crimson/Warped doors are better than others.

**Comment by joserobjr** [comment]
Thank you for reporting

**Comment by joserobjr** [comment]
It was a visualization issue, the doors were being saved correctly but the client were seeing them incorrectly.
