### ISSUE TITLE
Furnace does not work

### ISSUE THREAD

**Issue by Happmc2525** [PowerNukkit/PowerNukkit#393]
The furnace is not working in the latest bleeding build.
![Screenshot_20200719-204222](https://user-images.githubusercontent.com/60919012/87873938-98c3c900-ca00-11ea-94e1-c5e40b477ab5.png)

**Comment by tuilakhanh** [comment]
I can confirm this problem. It doesn't work with most of items

**Comment by joserobjr** [comment]
Thank you for reporting.
