### ISSUE TITLE
 Firework from dispenser only have 1 color

### ISSUE THREAD

**Issue by tuilakhanh** [PowerNukkit/PowerNukkit#397]
# 🐞 I found a bug

The fireworks released from the dispenser only have 1 color
### 📸 Screenshots / Videos

none

### ▶ Steps to Reproduce

 Firework from dispenser

### ✔ Expected Behavior

Its colored fireworks

### ❌ Actual Behavior

The fireworks are only black

### 📋 Debug information

* PowerNukkit version:  1.4.0.0-PN-SNAPSHOT
* Debug link: https://hastebin.com/fetonoyoje
* Timings link (if relevant): ✍

**Comment by Happmc2525** [comment]
There is only one type of potion from the dispenser
