### ISSUE TITLE
Spectator mode invalid behaviour

### ISSUE THREAD

**Issue by AntonPPDS** [PowerNukkit/PowerNukkit#400]
# 🐞 I found a bug
When switching to spectator mode (gamemode 3), the client can still break blocks.

### ▶ Steps to Reproduce

1. Run "/gamemode 3" command
2. Notice that you can still break blocks

### 📋 Debug information

* PowerNukkit version: 1.3.1.1-PN
* Minecraft version: v1.16.1 (Win10)

**Comment by AntonPPDS** [comment]
In addition, being in spectator mode and enabling fly mode may result kick with "Flying is not enabled on this server" message

**Comment by MrRazamataz** [comment]
When the client breaks blocks I believe it's only client side. You can check this be logging out and back in and seeing if the broken block is still there. This is with my experience though so yours might be different.

**Comment by AntonPPDS** [comment]
@MrRazamataz I have the same experience, my bad that I put it badly
