### ISSUE TITLE
Server does not shutdown after Watchdog triggered

### ISSUE THREAD

**Issue by AntonPPDS** [PowerNukkit/PowerNukkit#407]
# 🐞 I found a bug
When server freezes and Watchdog triggers, the server does not completely stop, which prevents the restart.

### ▶ Steps to Reproduce

1. Make Watchdog to trigger somehow (i.e. use [special plugin](https://github.com/AntonPPDS/WatchdogTrigger))
2. See that server does not completely stop

### 📋 Debug information

* PowerNukkit version: 1.3.1.1-PN

**Comment by joserobjr** [comment]
I'm going to try this tonight, but have you waited long enough?

Watchdog kill the JVM if the server does not stop gracefully 60 seconds after the message has been logged:
https://github.com/PowerNukkit/PowerNukkit/blob/1d329f9d43b1d8d17340f430a09c970e77672efe/src/main/java/cn/nukkit/utils/Watchdog.java#L36-L38

**Comment by AntonPPDS** [comment]
@joserobjr I waited an hour and the process is still running

**Comment by AntonPPDS** [comment]
Could [this](https://github.com/PowerNukkit/PowerNukkit/blob/master/src/main/java/cn/nukkit/Server.java#L900-L902) be the reason that Watchdog is not killing the server?

**Comment by joserobjr** [comment]
If `Disabling timings` gets logged, then yes, that could be the reason

**Comment by joserobjr** [comment]
Thank you for reporting!
