### ISSUE TITLE
Bug of cobble generator

### ISSUE THREAD

**Issue by junxiesky** [PowerNukkit/PowerNukkit#411]
### Expected Behavior

 cobble generator can work
![FIYW@ %1KQ1CT~YIS{9T)BS](https://user-images.githubusercontent.com/30452768/88463056-9ec71780-cee2-11ea-920c-2c115fba7d2d.png)

### Actual Behavior

Sometimes the cobble generator doesn't work
![4D(%~56EH2)WXMLLPA$@6AH](https://user-images.githubusercontent.com/30452768/88463074-b0a8ba80-cee2-11ea-91fe-a5e8af2a7e08.png)

### Steps to Reproduce

Dig holes and place magma and water as shown
![4D(%~56EH2)WXMLLPA$@6AH](https://user-images.githubusercontent.com/30452768/88463029-7a6b3b00-cee2-11ea-96bd-a1fc4e819f08.png)

### Debug information

* Debug link:
* Timings link (if relevant):

**Comment by joserobjr** [comment]
Hello, thank you for the report.

I'm trying to reproduce it but it is working as expected:
https://youtu.be/mtNvjG6XM7A

**Comment by joserobjr** [comment]
I'm going to close as stale because I couldn't reproduce the issue. If it is still happening, please, reopen with more information like a debug link from /debugpaste or maybe a short video.
