### ISSUE TITLE
Bed can be used far away which isn't expected like Vanilla

### ISSUE THREAD

**Issue by XKazzuKX** [PowerNukkit/PowerNukkit#425]
# 🐞 I found a bug
### ✔ Expected Behavior

https://youtu.be/Z4lipxcYFag

### ❌ Actual Behavior

https://youtu.be/jP8UE--jaWk

### 📋 Debug information

* PowerNukkit version: 1.3.1.1-PN (git-40da769)
* Debug link: https://debugpaste.powernukkit.org/pastes/suqujepalu

**Comment by good777LUCKY** [comment]
Available area (green area) (green stained glass = player legs position)
![Screenshot](https://user-images.githubusercontent.com/43497313/93654150-12a31d80-fa57-11ea-81ce-324a8199f064.jpg)
