### ISSUE TITLE
Bedrock 1.16 expels users / corrupts the world

### ISSUE THREAD

**Issue by Zero0101012** [PowerNukkit/PowerNukkit#434]
# 🐞 I found a bug
It was working fine a few days ago but yesterday I started to expel any player that enters the world and later showing that it cannot connect to the world, I thought it was some wrong plugin on my part but I reinstalled the entire system several times and what happened Same, apparently a part was corrupted since it shows an error with java.

**Comment by joserobjr** [comment]
Hello, please run the command /debugpaste so I can investigate it further. It's also important to share the complete error messages that you are receiving.

**Comment by joserobjr** [comment]
Closing as stale as we don't have enough information to investigate
