### ISSUE TITLE
Chorus bug

### ISSUE THREAD

**Issue by Jl1mbo** [PowerNukkit/PowerNukkit#436]
# 🐞 I found a bug

Chorus a bug

### ▶ Steps to Reproduce

1. Grow a chorus
2. Break the bottommost block of the chorus plant

### ✔ Expected Behavior

Having broken the lowest block, everything falls

### ❌ Actual Behavior

Having broken the lowest block, everything does not fall off, but remains to fly

### 📋 Debug information

* PowerNukkit version: last

**Comment by joserobjr** [comment]
Thank you for the report! :)
