### ISSUE TITLE
Nether sky bug

### ISSUE THREAD

**Issue by Happmc2525** [PowerNukkit/PowerNukkit#437]
# 🐞 I found a bug
The sky in the Nether is strange

### 📸 Screenshots / Videos
![2020-08-08](https://user-images.githubusercontent.com/60919012/89708973-a85a8000-d9b6-11ea-9fa8-7292237142e4.png)

### 📋 Debug information
* PowerNukkit version: f2e9a5e
* Debug link: https://debugpaste.powernukkit.org/pastes/eqogeyazaf

**Comment by joserobjr** [comment]
Linking related issues:
#21 CloudburstMC#839

**Comment by joserobjr** [comment]
Thank you for the report! 👍
