### ISSUE TITLE
Minecarts can drop more than once

### ISSUE THREAD

**Issue by SS-YG** [PowerNukkit/PowerNukkit#443]
If you attack overlapped harvesters quickly, there is a high probability that one more harvester will come out.
Sorry, I don't know if my grammar is correct. It is translated by software.

**Comment by SS-YG** [comment]
debugpaste = https://hastebin.com/yakiqazobi

**Comment by SS-YG** [comment]
"harvesters" is 
![image](https://user-images.githubusercontent.com/69110760/89725150-19457a80-da3f-11ea-991f-b11e557877b6.png)

**Comment by joserobjr** [comment]
Thank you. I understood what you mean. The image helped.
