### ISSUE TITLE
Something is wrong with jungle leaves

### ISSUE THREAD

**Issue by joserobjr** [PowerNukkit/PowerNukkit#455]
# 🐞 I found a bug

### 📸 Screenshots / Videos

https://www.youtube.com/watch?v=iUgspxp_bfM

### ▶ Steps to Reproduce

1. Use the world from #410
2. Set randomTickSpeed 3 and showCoordinates to true
3. Make it become day so you can see better
4. Go in creative mode and get a fireball item
5. Fly to 144 74 169
6. Ignite a jungle leave using the fireball
7. The leaves will change, spreading from where the fireball has ignited the leave

### ✔ Expected Behavior

Just show the fire and do nothing visible

### ❌ Actual Behavior

It spreads a leaves change

### 📋 Debug information

* Debug link: https://debugpaste.powernukkit.org/pastes/yubaxepexe

**Comment by AntonPPDS** [comment]
I debugged this and realized what is happening [here](https://github.com/PowerNukkit/PowerNukkit/blob/2edaf02b6973b4b48fd5bdacc0bcae4d5dd7aa0a/src/main/java/cn/nukkit/block/BlockLeaves.java#L124)

**Comment by joserobjr** [comment]
Might be a block state to runtime id mapping issue

**Comment by AntonPPDS** [comment]
Also affects spruce, but not visualy

**Comment by AntonPPDS** [comment]
Another steps to reproduce:
1. Plant 4 dark oak saplings and let them grow
2. Break leaves
3. Leaves all around make a wave

**Comment by joserobjr** [comment]
The wave is expected, it's the way the server detects changes to the structure of the tree and tries to decay on random ticks. But the check decay flag should not be visible to the player

**Comment by joserobjr** [comment]
The wave should be happening but it shouldn't be visible
