### ISSUE TITLE
Certain 1.16 blocks dissapear

### ISSUE THREAD

**Issue by bobbyl140** [PowerNukkit/PowerNukkit#456]
Certain blocks from the recent 1.16 update don’t work, such as Crimson and Warped Planks, Blackstone, and Crying Obsidian. These blocks (and others from this version) work in the inventory, but on placing they immediately dissapear.

**Comment by bobbyl140** [comment]
https://hastebin.com/dojizocira

**Comment by joserobjr** [comment]
They aren't implemented in the stable releases yet. They are currently available only in the bleeding branch. They are planning to be released at 1.4.0.0-PN

**Comment by joserobjr** [comment]
Thank you for the report anyway 😁 👍

**Comment by bobbyl140** [comment]
How would I go about installing this? I tried the same method used for the stable release (mvnw clean package) and it gave a bunch of errors. (I’m new to this so I have no idea what they mean.) Is there some different command I should run?  Sent from Mail for Windows 10 From: joserobjrSent: Monday, August 10, 2020 5:19 PMTo: PowerNukkit/PowerNukkitCc: bobbyl140; MentionSubject: Re: [PowerNukkit/PowerNukkit] Certain 1.16 blocks dissapear (#456) Closed #456.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by joserobjr** [comment]
It's the same command, you can also get the latest builds from the [GitHub Actions](https://github.com/PowerNukkit/PowerNukkit/actions?query=branch%3Ableeding+workflow%3A%22PowerNukkit+v1.X%22) or from the [Maven Central Snapshots](https://oss.sonatype.org/content/repositories/snapshots/org/powernukkit/powernukkit/) Repository. There are plans to make the bleeding distributions easier using our main website https://powernukkit.org .

The latest build at the time of writing can be downloaded at https://oss.sonatype.org/content/repositories/snapshots/org/powernukkit/powernukkit/1.4.0.0-PN-SNAPSHOT/powernukkit-1.4.0.0-PN-20200811.010320-14-shaded.jar
