### ISSUE TITLE
The direction of the door is strange

### ISSUE THREAD

**Issue by Happmc2525** [PowerNukkit/PowerNukkit#458]
# 🐞 I found a bug
It's happening in the latest bleeding build

### 📸 Screenshots / Videos
![Screenshot_20200811-103120](https://user-images.githubusercontent.com/60919012/89847458-0bb6fe80-dbbf-11ea-84ae-6e5c5c34d995.png)

### 📋 Debug information
* Debug link: https://debugpaste.powernukkit.org/pastes/uvisidubet

**Comment by joserobjr** [comment]
Hello, I'm trying to replicate the door placement inconsistency but it is working as expected.

It's also possible to arrange the doors as in the screenshot in single-player. What is the block placement order that don't match the vanilla behaviour?

**Comment by joserobjr** [comment]
Hi, I'm going to close as stale because I couldn't reproduce the issue. If it is still happening, please, reopen with more information on how to reproduce it, maybe by a short video or more detailed steps.
