### ISSUE TITLE
The bookshelf becomes a command block

### ISSUE THREAD

**Issue by BlockCityNetwork** [PowerNukkit/PowerNukkit#459]
# 🐞 I found a bug
The bookshelf becomes a command block.

### ▶ Steps to Reproduce
1.Get a bookshelf from the backpack or use the /give command.
2. Place the bookshelf on the ground.

### ✔ Expected Behavior
A normal bookshelf is placed on the ground.

### ❌ Actual Behavior
When the bookshelf is placed on the floor, it immediately turns into a command block.

### 📋 Debug information
* PowerNukkit version: Nukkit 1.3.1.2-PN (git-9371c6f) "PowerNukkit" API version 1.0.11 Minecraft: BE V1.16.0 (Protocol version 407)

### 💬 Anything else we should know?
When the bookshelf in the backpack, it is still a bookshelf and the ID is 47,too.

**Comment by Happmc2525** [comment]
https://github.com/PowerNukkit/PowerNukkit/issues/311

**Comment by joserobjr** [comment]
Are you using the  VanillaCommandBlock plugin?

**Comment by BlockCityNetwork** [comment]
> 您是否在使用VanillaCommandBlock插件？

In fact, it is.I'm going to delete it and try again.

**Comment by BlockCityNetwork** [comment]
> [＃311](https://github.com/PowerNukkit/PowerNukkit/issues/311)

God, I didn't see this issue. Sorry.

**Comment by joserobjr** [comment]
No problem, thank you for the report anyway, that could be a brand new issue 😃 👍
