### ISSUE TITLE
The animation that breaks blocks is strange

### ISSUE THREAD

**Issue by Happmc2525** [PowerNukkit/PowerNukkit#460]
# 🐞 I found a bug
This happens in latest bleeding build

### 📸 Screenshots / Videos
https://youtu.be/R_S9lp1jyow

### 📋 Debug information
* Debug link: https://debugpaste.powernukkit.org/pastes/quwakolehe

**Comment by joserobjr** [comment]
Thank you for the report. The break time is broken. It's being reworked at #370
