### ISSUE TITLE
Nether crash

### ISSUE THREAD

**Issue by Jl1mbo** [PowerNukkit/PowerNukkit#467]
# 🐞 I found a bug

If you leave the server in Nether, then when you re-enter the server, the client crashes

### ▶ Steps to Reproduce

1. Log into the server and teleport to Nether
2. Log out server
3. Login again
4. Look and regret that you went to Nether, because you will not come back, the client will crash

### ✔ Expected Behavior

You can login again

### ❌ Actual Behavior

can't log in again

### 📋 Debug information

* PowerNukkit version: last bleeding

**Comment by joserobjr** [comment]
Hi @Jl1mbo , please check if this build fixes the issue, I couldn't reproduce the crash but I noticed that the Nether had overworld sky after reconnecting, this might be the root cause of your crash.

https://github.com/PowerNukkit/PowerNukkit/actions/runs/205850425

**Comment by Jl1mbo** [comment]
Thank you, it works.
