### ISSUE TITLE
Wall Connection rule has been updated in 1.16.20

### ISSUE THREAD

**Issue by good777LUCKY** [PowerNukkit/PowerNukkit#483]
# ❇ Feature Request

### 📸 Screenshots / Videos

-

### ✔ Expected Behavior

Now wall can connect with opened trapdoor.

### ❌ Actual Behavior

Not connected.

### 💬 Anything else we should know?

- https://bugs.mojang.com/browse/MCPE-79490
- https://feedback.minecraft.net/hc/en-us/articles/360046901272-Minecraft-1-16-20-Bedrock-

**Comment by joserobjr** [comment]
I saw that in the changelog but I tested in a survival world and I couldn't notice any different behavior with trapdoor

**Comment by good777LUCKY** [comment]
> I saw that in the changelog but I tested in a survival world and I couldn't notice any different behavior with trapdoor

![image-2020-05-21-00-06-23-170](https://user-images.githubusercontent.com/43497313/90336777-03285300-e019-11ea-84fe-a2bdf7c1c914.png)
This feature has been added

**Comment by joserobjr** [comment]
Oh, now it makes sense! Thank you!

**Comment by joserobjr** [comment]
The new feature affects everything that has connections:
![image](https://user-images.githubusercontent.com/3679022/90337106-b6139500-dfb6-11ea-997f-f8ddd184e37c.png)
