### ISSUE TITLE
Piston is not working properly with melon

### ISSUE THREAD

**Issue by tuilakhanh** [PowerNukkit/PowerNukkit#486]
# 🐞 I found a bug

Piston is not working properly with melon
### 📸 Screenshots / Videos

https://photos.app.goo.gl/fdwvBeHLZuNSZ22h6

### ▶ Steps to Reproduce

Push melon by piston

### ✔ Expected Behavior

melon drops into pieces of melon

### ❌ Actual Behavior

Melon is pushed by piston

### 📋 Debug information

* PowerNukkit version: ✍
* Debug link: https://debugpaste.powernukkit.org/pastes/koxamuwike
* Timings link (if relevant): ✍

**Comment by joserobjr** [comment]
Thank you
