### ISSUE TITLE
Fix Haste Effect and Health_Boost

### ISSUE THREAD

**Issue by SenseiTarzan** [PowerNukkit/PowerNukkit#490]
# 🐞 I found a bug

### 📸 Screenshots / Videos

I can't record because I have problems with my computer and phone when I start a record.

### 📋 Debug information

* PowerNukkit version: 1.14.0-PN
* Debug link: 
![image](https://user-images.githubusercontent.com/32621158/90423356-95cdfe00-e0bc-11ea-8043-a63a563db2ac.png)

* Timings link (if relevant): https://timings.aikar.co/?id=71a1c79d7fa84352890e5575c0fac841

### 💢 Crash Dump, Stack Trace and Other Files

no error

**Comment by joserobjr** [comment]
Hello, thank you for opening an issue.

What is not working with haste effect and health boost?

**Comment by SenseiTarzan** [comment]
**########Haste#########**

### when you have the haste effect and break a block the effect is removed.

**#####Health Boost######**
### For the health boost effect, the effect is to remove the maxhealth and always to the number of life added by the health boost effect.
