### ISSUE TITLE
Health regain bug

### ISSUE THREAD

**Issue by Iktaniyalol** [PowerNukkit/PowerNukkit#494]
# 🐞 I found a bug

### 📸 Screenshots / Videos
video: https://youtu.be/3_2blSMQVnA

### ▶ Steps to Reproduce
1. try to get damaged
2. wait until your health is restored and hunger starts to be spent

### ✔ Expected Behavior
health regeneration should spend saturation and hunger level.

### ❌ Actual Behavior
health regeneration ignore saturation, spend hunger level below 17. But it is fake.

### 📋 Debug information

* PowerNukkit version: 1.3.1.4-PN-CUSTOM ad2d25c
* Debug link: https://debugpaste.powernukkit.org/pastes/jivumefabe
* Timings link (if relevant):

**Comment by Iktaniyalol** [comment]
> # 🐞 I found a bug
> ### 📸 Screenshots / Videos
> video: https://youtu.be/3_2blSMQVnA
> 
> ### ▶ Steps to Reproduce
> 1. try to get damaged
> 2. wait until your health is restored and hunger starts to be spent
> 
> ### ✔ Expected Behavior
> health regeneration should spend saturation and hunger level.
> 
> ### ❌ Actual Behavior
> health regeneration ignore saturation, spend hunger level below 17. But it is fake.
> 
> ### 📋 Debug information
> * PowerNukkit version: 1.3.1.4-PN-CUSTOM
> * Debug link:
> * Timings link (if relevant):
> 
> ### 💢 Crash Dump, Stack Trace and Other Files
> ### 💬 Anything else we should know?

https://hastebin.com/jivumefabe

**Comment by joserobjr** [comment]
Thank you for reporting
