### ISSUE TITLE
ender chest bug

### ISSUE THREAD

**Issue by Happmc2525** [PowerNukkit/PowerNukkit#502]
# 🐞 I found a bug
Placing ender chests does not reduce the number of ender chests you have.

### ▶ Steps to Reproduce
place ender chest in Survival mode

### 📋 Debug information
* Debug link: https://debugpaste.powernukkit.org/pastes/ebuqixefef
* 1.4.0.0-PN-SNAPSHOT at 44ef78e

**Comment by good777LUCKY** [comment]
When I place ender chest in Survival mode, there is animation that block reduce(like shaking block in inventory), but count will not reduce. Also, I can open ender chest inventory with duplicated ender chest and when I rejoin server, there is duplicated ender chest.

**Comment by joserobjr** [comment]
Thank you, the issue is fixed in the bleeding branch
