### ISSUE TITLE
Eating animation is not canceled in spectator mode

### ISSUE THREAD

**Issue by LoboMetalurgico** [PowerNukkit/PowerNukkit#503]
# 🐞 I found a bug

### 📸 Screenshots / Videos
No have now, sorry.

### ▶ Steps to Reproduce

1. Get any food
2. Go to spectator mode
3. Try Eat

### ✔ Expected Behavior

The animation of eating being canceled

### ❌ Actual Behavior

Eating animation is not canceled

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT
* Debug link: https://debugpaste.powernukkit.org/pastes/padidokowe

**Comment by joserobjr** [comment]
I don't think it is possible to cancel the animation entirely since it's done by the client side and the client don't have spectator mode, it's a packet trick.

If anybody have an idea on how to stop it, share with us on https://powernukkit.org/discord
