### ISSUE TITLE
Bug for TOTEM

### ISSUE THREAD

**Issue by Jl1mbo** [PowerNukkit/PowerNukkit#517]
# 🐞 I found a bug

Totem does not save from everything

### ✔ Expected Behavior

If you burn in any way with a totem, then it will save you

### ❌ Actual Behavior

If you burn in any way with a totem, then it will not save you

### 📋 Debug information

* PowerNukkit version: ✍PowerNukkit v1.3.1.4-PN

**Comment by joserobjr** [comment]
> ????

Thats a bot that detects the related version and commits from the message
