### ISSUE TITLE
Random people being opped

### ISSUE THREAD

**Issue by bobbyl140** [PowerNukkit/PowerNukkit#520]
### Expected Behavior
OP list is controlled with /op and /deop

### Actual Behavior
Server randomly OPs people, possibly on join

### Steps to Reproduce
The bug is really always active, I go into the server files at random times and a bunch of people are opped

### Debug information

* Debug link:  https://debugpaste.powernukkit.org/pastes/fudepotapo
* Timings link (if relevant):

**Comment by MrRazamataz** [comment]
Just to say the Vanilla Command Block plugin will turn book cases into repeating command blocks and that plugin doesn't work with powernukkit anyway.

**Comment by good777LUCKY** [comment]
> Just to say the Vanilla Command Block plugin will turn book cases into repeating command blocks and that plugin doesn't work with powernukkit anyway.

Check #311

**Comment by MrRazamataz** [comment]
> > Just to say the Vanilla Command Block plugin will turn book cases into repeating command blocks and that plugin doesn't work with powernukkit anyway.
> 
> Check #311 

Wait so it works again now?

**Comment by joserobjr** [comment]
Can you reproduce this issue without plugins?

**Comment by bobbyl140** [comment]
i hadn't thought of that, i bet it's a plugin. Let me try some of those and then try without plugins.
