### ISSUE TITLE
Enchanting with lapislazuli custom compounttag

### ISSUE THREAD

**Issue by MrClean1337** [PowerNukkit/PowerNukkit#523]
# 🐞 I found a bug with Enchanting with lapislazuli custom compounttag
You can choose an enchantment as you want with some lapislazuli that has been signend (custom compounttag with "LORE")

### 📸 Screenshots / Videos
None just tried it right now

### ▶ Steps to Reproduce
1. Take some amount of lapislazuli
2. Change the compounttag like sign a item. (Add LORE/Displayname)
3. Put it in the enchantingtable
4. Click on enchant
5. Repeat 1. - 4.

### ✔ Expected Behavior
Enchant or not Enchant (Default bedrock behavior)

### ❌ Actual Behavior
Clientside: It will be enchanted
Serverside: It wont enchant and you wont loose xp/lapis (Pickup an xporb to regen all the clientside-lost levels)

### 📋 Debug information
Nukkit 1.3.1.4-PN (git-9b26d13) "PowerNukkit" (API: 1.0.11)

### 💢 Crash Dump, Stack Trace and Other Files
[ERROR] Player MrClean2349 does not have enchant window open

### 💬 Anything else we should know?
- Low level prio

**Comment by joserobjr** [comment]
Thank you for the report. I tried to reproduce today with 1.4.0.0-PN-SNAPSHOT 16785355985ab0d3dd1c5d30788a535401372a7c but I could not reproduce it. I think it was already fixed by some commit.

Closing as stale (resolved but it's hard to know which commit solved it)
