### ISSUE TITLE
Cancelling CraftItemEvent makes you loose the recipe

### ISSUE THREAD

**Issue by joserobjr** [PowerNukkit/PowerNukkit#526]
# 🐞 I found a bug

It was reported by discord:
> I have a problem with some craft that I blocked for some xp levels with the CraftItemEvent and it loses their item that allows to craft
> Here's my problem: I block recipes at certain levels of the player's xp and the item in the set up will be deleted.

### 📸 Screenshots / Videos

https://youtu.be/WS-3TKgsjPI

### ▶ Steps to Reproduce

1. Cancel the CraftItemEvent using a plugin
2. Attempt to craft as indicated in the video
3. The ingredients will be lost

### ✔ Expected Behavior

Don't loose ingredients and reverse the crafting in the player GUI

### ❌ Actual Behavior

The crafted items and the ingredients disappear

### 📋 Debug information

* PowerNukkit version: 1.3.1.4-PN or 1.4.0.0-PN-SNAPSHOT

**Comment by SenseiTarzan** [comment]
**Good evening, I think I found the cause of the bug, but I don't know how to fix it is the SlotChangeAction.**
