### ISSUE TITLE
Bell Chaos when using a lever

### ISSUE THREAD

**Issue by Plugner** [PowerNukkit/PowerNukkit#540]
# 🐞 I found a bug

### 📸 Screenshots / Videos

https://imgur.com/a/JarHbQM

### ▶ Steps to Reproduce

1. Get a Stained glass in your hand.
2. Place a bell.
3. Place a lever.
4. Press in the lever with SHIFT.

### ✔ Expected Behavior

Do not make chaos.

### ❌ Actual Behavior

Making a Chaos of Sound.

### 📋 Debug information

* PowerNukkit version: ✍ 1.3.1.4-PN
* Debug link: ✍https://debugpaste.powernukkit.org/pastes/xoqihesufe

**Comment by joserobjr** [comment]
Hi, thank you for the report, this issue was already fixed in 1.4.0.0-PN-SNAPSHOT at #496 😊
