### ISSUE TITLE
Not able to use Enchanted Book in Grindstone

### ISSUE THREAD

**Issue by good777LUCKY** [PowerNukkit/PowerNukkit#548]
# 🐞 I found a bug

### 📸 Screenshots / Videos

-

### ▶ Steps to Reproduce

1. Put Enchanted Book in Grindstone and get the result(book)
2. It will reset to Enchanted Book

### ✔ Expected Behavior

When I use Enchanted Book in Grindstone, it will give xp and book.

### ❌ Actual Behavior

It doesn't give xp and book.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-SNAPSHOT (https://github.com/PowerNukkit/PowerNukkit/commit/2b5be8d483865ce811999520b301ae6294a92ff5)
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

No Crash

**Comment by joserobjr** [comment]
How the experience should work:
When removing enchantments from items, the player gains experience equal to the minimum modified enchantment level of that enchantment. The final amount is a uniformly-distributed random amount between half the resulting sum (rounded up) and the sum itself

**Comment by joserobjr** [comment]
Thank you for reporting :)
