### ISSUE TITLE
Bed Behaviour Bug

### ISSUE THREAD

**Issue by Poswn** [PowerNukkit/PowerNukkit#550]
# 🐞 I found a bug
### ✔ Expected Behavior

In vanilla there is a certain distance where your told your bed is too far away when trying to go into it, the video below is from Minecraft Vanilla 1.16.20
https://streamable.com/zqgbfv

### ❌ Actual Behavior

In powernukkit there is no distance to stop you from going in anywhere which is not like the vanilla behaviour, the video below explains it
https://streamable.com/mkavjo

### 📋 Debug information

* PowerNukkit version: 1.3.1.5
* Debug link: https://debugpaste.powernukkit.org/pastes/ijohenemod

**Comment by good777LUCKY** [comment]
I think it is duplicated with #425

**Comment by joserobjr** [comment]
Thank you for the report, It's indeed duplicated of #425 I suggest subscribing to notifications on that report to be notified when the issue gets fixed.
