### ISSUE TITLE
Breaking an ice with a silk touch

### ISSUE THREAD

**Issue by IrineuMC** [PowerNukkit/PowerNukkit#554]
When breaking an ice with a silk touch enchantment, **it turns into water and even drops the ice!**
Could you fix this bug?

**Comment by Plugner** [comment]
Hi! 
Please send your PowerNukkit version, we will try to remake the bug, and fix that.
Thanks (:

**Comment by Plugner** [comment]
Hi!
I've detected this bug is working in 1.3.1.5-PN (the latest version), I'm working to fix that.
Thanks for the report (:

**Comment by IrineuMC** [comment]
Yes, it is the latest version! Thanks for correcting 🙂

**Comment by Plugner** [comment]
(:

**Comment by joserobjr** [comment]
Thank you for reporting and solving, you are awesome people 👍
