### ISSUE TITLE
Shield don't stop blocking when you attack

### ISSUE THREAD

**Issue by hinexmine** [PowerNukkit/PowerNukkit#562]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Put a shield in your off-hand
2. Keep sneaked
3 Attack

### ✔ Expected Behavior

* Shield stop blocking
* The attack animation happens
* Shield start blocking again after a few moments

### ❌ Actual Behavior

The attack animation happens but you never stop blocking

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT at 838036e

### 💢 Crash Dump, Stack Trace and Other Files

None

#### Original Message
1) When you hit with a shield on a shift, the shield still stands still, in vanilla minecraft, when you hit, the shield leaves and comes
2) There is no gravel or algae in the water, please fix it!
3) A portal to the end is created but it is impossible to get into it

🛡️Forgive me if there are mistakes, I am Russian and do not know English well

**Comment by joserobjr** [comment]
Thank you for reporting.

The shield issue is confirmed.

> 2)There is no gravel or algae in the water, please fix it!
The new world gen isn't implemented yet.


> 3)A portal to the end is created but it is impossible to get into it
The End dimension isn't implemented yet. But you can use this plugin meanwhile:
https://discuss.powernukkit.org/t/theend-plugin-v1-1-0/69

**Comment by hinexmine** [comment]
I have had a plug-in for the end for a long time, thanks for the answer!

**Comment by joserobjr** [comment]
The shield issue was fixed in 1.4.0.0-PN, the other issues will be handled in #584 and #589 👍
