### ISSUE TITLE
When I squat down, I still can't put squares on the workbench(Crafting Table).

### ISSUE THREAD

**Issue by SS-YG** [PowerNukkit/PowerNukkit#578]
**Improved text:**
I still can't place blocks against the crafting table when I sneak. ~~ Player is attempting to place a block next to a crafting table while sneaking
It shows the Crafting Table GUI instead ~~ The GUI opens, but it shouldn't
The block is placed only in my view. From the perspective of another player, the block is not there. ~~ And causes a client desync

----
**Original text:**

When I squat down, I still can't put squares on the workbench(Crafting Table).
He will show the GUI of the Crafting Table.
From my point of view of the game, this placed block exists. But from the perspective of other players, this block doesn't exist.

**Comment by SS-YG** [comment]
debugpaste = https://hastebin.com/aqagoleqap

**Comment by joserobjr** [comment]
Thank you for the report 👍

**Comment by Gabriel8579** [comment]
I could not reproduce anymore at 1.4.0.0-PN-SNAPSHOT (git-35949fb4), closing as stale
