### ISSUE TITLE
Shields don't work

### ISSUE THREAD

**Issue by Jl1mbo** [PowerNukkit/PowerNukkit#583]
# 🐞 I found a bug
Shields don't work

### ✔ Expected Behavior

When hitting the shield, the striking player is knocked back

### ❌ Actual Behavior

Nothing happens

### 📋 Debug information

* Debug link: ✍https://debugpaste.powernukkit.org/pastes/asoxizariy

**Comment by tuilakhanh** [comment]
Shileds already implemented in bleeding branch

**Comment by Jl1mbo** [comment]
Okay @tuilakhanh

**Comment by joserobjr** [comment]
Thank you for the report. It was already fixed by #351
