### ISSUE TITLE
Opening working blocks on shift

### ISSUE THREAD

**Issue by Jl1mbo** [PowerNukkit/PowerNukkit#590]
# 🐞 I found a bug
On the shift, you can open the Stove, workbench, enchanting table, chest, chest, trap, funnel, anvil, ender chest, etc.

### ✔ Expected Behavior
They cannot be opened on the shift

### ❌ Actual Behavior
They open on the shift

### 📋 Debug information

* PowerNukkit version: ✍ last

**Comment by tuilakhanh** [comment]
Fixed at # 403
