### ISSUE TITLE
Arrow can flow in flowing water and generate a lot of particle

### ISSUE THREAD

**Issue by good777LUCKY** [PowerNukkit/PowerNukkit#593]
# 🐞 I found a bug

### 📸 Screenshots / Videos

(Sorry, I don't have it)

### ▶ Steps to Reproduce

1. Shoot arrow to flowing water.
2. Arrow will cause a lot of particle and it will flow in the water.

### ✔ Expected Behavior

Arrow can't flow in the water because it will stop at block.

### ❌ Actual Behavior

It will flow in the water and generate a lot of particle. (laggy)

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-SNAPSHOT (17d8b17c7210a4bc6d77c33d9605fd1d3436610e)
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

(Doesn't crash)

### 💬 Anything else we should know?

Also, arrow with fire will cause more lag because of smoke particle. (It doesn't stop generating)

**Comment by joserobjr** [comment]
Thank you for the report! 👍

**Comment by good777LUCKY** [comment]
I think bubble particle problem is not fixed.
![Screenshot_20200914-163903_Minecraft](https://user-images.githubusercontent.com/43497313/93057756-61dcfd00-f6a9-11ea-85db-ac7b2d1160d4.jpg)

**Comment by joserobjr** [comment]
Thank you for the print. I just found the cause.
