### ISSUE TITLE
Can't Open Inventory if you're riding Vehicle

### ISSUE THREAD

**Issue by GoodLucky777** [PowerNukkit/PowerNukkit#599]
# 🐞 I found a bug

### 📸 Screenshots / Videos

(Sorry, I don't have it.)

### ▶ Steps to Reproduce

1. Ride something like Boat or Minecart.
2. Open Inventory but it will not open

### ✔ Expected Behavior

You can open inventory.

### ❌ Actual Behavior

You can't open it.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-SNAPSHOT (cbbe51f719000bbaaa708f6158535f5eddf5c9e8)
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

It doesn't crash.

**Comment by LoboMetalurgico** [comment]
Fixed in #986
