### ISSUE TITLE
Can't craft black concrete powder with black dye

### ISSUE THREAD

**Issue by good777LUCKY** [PowerNukkit/PowerNukkit#600]
# 🐞 I found a bug

### 📸 Screenshots / Videos

(Sorry, I don't have it.)

### ▶ Steps to Reproduce

1. Craft black concrete powder.
2. Server will refuse craft request.

### ✔ Expected Behavior

It is craft able.

### ❌ Actual Behavior

Not able to craft it.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-SNAPSHOT (cbbe51f719000bbaaa708f6158535f5eddf5c9e8)
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

Log:
![Error_log](https://user-images.githubusercontent.com/43497313/93276606-f86d0380-f7fa-11ea-989e-5fab8d570b14.jpg)

**Comment by joserobjr** [comment]
Can you take a screenshot of the recipe? I can't reproduce it here.
https://www.youtube.com/watch?v=fqIEFz21Kt8

**Comment by good777LUCKY** [comment]
> Can you take a screenshot of the recipe? I can't reproduce it here.
> https://www.youtube.com/watch?v=fqIEFz21Kt8

I used a Black Dye instead of Ink Sac.

**Comment by joserobjr** [comment]
Thank you!
