### ISSUE TITLE
Shield can protect player from lightning bolt

### ISSUE THREAD

**Issue by good777LUCKY** [PowerNukkit/PowerNukkit#603]
# 🐞 I found a bug

### 📸 Screenshots / Videos

(Sorry, I don't have it.)

### ▶ Steps to Reproduce

1. Hold a shield
2. Hit by lightning bolt

### ✔ Expected Behavior

You will get damage.

### ❌ Actual Behavior

You will not get damage.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-SNAPSHOT (3ec61a4be178e25e5ab9657cf2caabaf82fc78c8)
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

It doesn't crash.

**Comment by joserobjr** [comment]
Thank you, should be solved now. Please reopen if it is still happening.
