### ISSUE TITLE
Bed explosion power is not correct

### ISSUE THREAD

**Issue by GoodLucky777** [PowerNukkit/PowerNukkit#609]
# ❇ Feature Request

### ✔ Expected Behavior

When you try use a bed in nether or end dimensions, it will explode. (power: 5) And also, it makes fire.

### ❌ Actual Behavior

It will spawn a TNT(fuse: 0)(power: 4).

### 💬 Anything else we should know?

https://minecraft.gamepedia.com/Explosion

**Comment by joserobjr** [comment]
IKR haha that came from the upstream, I was going to make it explode properly but I forgot, thank you for reporting
