### ISSUE TITLE
Shield can protect player from fall damage

### ISSUE THREAD

**Issue by good777LUCKY** [PowerNukkit/PowerNukkit#610]
# 🐞 I found a bug

### 📸 Screenshots / Videos

(Sorry, I don't have it.)

### ▶ Steps to Reproduce

1. Fall and hold a shield
2. The player will not get fall damage.

### ✔ Expected Behavior

The shield can not protect from fall damage.

### ❌ Actual Behavior

It will protect the player.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-SNAPSHOT (0b4d551f4dd7fd9996ead5015ea9cd80435aac4d)
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

It doesn't crash.

**Comment by joserobjr** [comment]
Hello, I could not reproduce the issue:
https://youtu.be/BGvKVchwS9U

**Comment by good777LUCKY** [comment]
I think it was something like lag or other thing. Closing this issue.
