### ISSUE TITLE
scaffolding stacking does not work correctly

### ISSUE THREAD

**Issue by Superzock3003** [PowerNukkit/PowerNukkit#616]
# 🐞 I found a bug

### 📸 Screenshots / Videos
https://youtu.be/pOMDnuxPlf0

### ▶ Steps to Reproduce
1. Place a scaffolding 
2. Place a second scaffolding a few blocks above the first one

### ✔ Expected Behavior
The scaffoldings will stack

### ❌ Actual Behavior
The scaffholding is plopping off (like sand lands on a torch)

### 📋 Debug information
* PowerNukkit version: 1.4.0.0-SNAPSHOT (6966b19)
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files
It doesn't crash.

**Comment by Superzock3003** [comment]
Fixed

**Comment by LoboMetalurgico** [comment]
Fixed in upstream
