### ISSUE TITLE
Item go through a block Problem

### ISSUE THREAD

**Issue by good777LUCKY** [PowerNukkit/PowerNukkit#624]
# 🐞 I found a bug

### 📸 Screenshots / Videos

![Screenshot](https://user-images.githubusercontent.com/43497313/76484036-04e35e80-645c-11ea-9a9d-27e857dbb062.gif)

### ▶ Steps to Reproduce

1. Throw any item on block that shape is like grass block.
2. The item will sink if it is near to center of block.

### ✔ Expected Behavior

It will not sink.

### ❌ Actual Behavior

It will sink.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-SNAPSHOT (6966b19b2d104d883e319403312c5e33321b0b13)
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

It doesn't crash.

### 💬 Anything else we should know?

https://github.com/CloudburstMC/Nukkit/issues/1254

**Comment by joserobjr** [comment]
Thank you 👍
