### ISSUE TITLE
Dry Sponge will remove water-logged block

### ISSUE THREAD

**Issue by GoodLucky777** [PowerNukkit/PowerNukkit#643]
# 🐞 I found a bug

### 📸 Screenshots / Videos

(Sorry, I don't have it.)

### ▶ Steps to Reproduce

1. Make any water-logged block that water-logging level is 1.
2. Build a dry Sponge.
3. Water-logged block will be removed. (Water was not removed. #94)

### ✔ Expected Behavior

It will remove a water block not the water-logged block.

### ❌ Actual Behavior

It will remove the water-logged block.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-SNAPSHOT (db0a1d217f65a39fa142b23b9a6bf6eee090bfb6)
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

It doesn't crash.

**Comment by LoboMetalurgico** [comment]
FIxed in #967
