### ISSUE TITLE
The piston can't push off the watermelon. The pumpkin can

### ISSUE THREAD

**Issue by zhizi520** [PowerNukkit/PowerNukkit#644]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: ✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by tuilakhanh** [comment]
Fixed at #488

**Comment by joserobjr** [comment]
Thank you for the report! I have good news, this issue was already solved at #488 and the fix is already in the snapshot for the next version. So I'm going to close it as duplicate because it was previously reported at #486
