### ISSUE TITLE
buggs trains place hopper

### ISSUE THREAD

**Issue by davee261** [PowerNukkit/PowerNukkit#649]
please add so that the tracks can be laid on the hopper

the latest version of the game    PowerNukkit v1.3.1.5-PN (Security Update)

**Comment by good777LUCKY** [comment]
It was fixed in 1.4.0.0 SNAPSHOT

**Comment by davee261** [comment]
> To bylo opraveno v 1.4.0.0 SNAPSHOT ( [# 432](https://github.com/PowerNukkit/PowerNukkit/pull/432) )

and when will it be officially released? I don't want anything to crash or something

**Comment by davee261** [comment]
> It was fixed in 1.4.0.0 SNAPSHOT (#432)

where can i find 1.4 to download it? I can not find her

**Comment by good777LUCKY** [comment]
> > It was fixed in 1.4.0.0 SNAPSHOT (#432)
> 
> where can i find 1.4 to download it? I can not find her

You can find here https://powernukkit.org/snapshot

**Comment by davee261** [comment]
> > > It was fixed in 1.4.0.0 SNAPSHOT (#432)
> > 
> > 
> > where can i find 1.4 to download it? I can not find her
> 
> You can find here https://powernukkit.org/snapshot

download this? nwm exactly what I don't know about it https://github.com/PowerNukkit/PowerNukkit/suites/1250437454/artifacts/19034027

**Comment by joserobjr** [comment]
Thank you for the report! I have good news, this issue was already solved at #432 and the fix is already in the snapshot for the next version. So I'm going to close it as duplicate because it was previously reported at #426
