### ISSUE TITLE
Crash server 1.4.0.0 bug ram 

### ISSUE THREAD

**Issue by davee261** [PowerNukkit/PowerNukkit#657]
hello, in version 1.4.0.0 there is a big problem I turn on the server runs but gradually eats more ram and then exceeds the limit and the server crashes

**Comment by MrRazamataz** [comment]
> hello, in version 1.4.0.0 there is a big problem I turn on the server runs but gradually eats more ram and then exceeds the limit and the server crashes

How much RAM have you got on your server?
