### ISSUE TITLE
Bedrock boxes (Lava generation replacing bedrock)

### ISSUE THREAD

**Issue by Jl1mbo** [PowerNukkit/PowerNukkit#664]
# 🐞 I found a bug
The second time I recreate the world, boxes from the bedrock appear at different coordinates

**Comment by joserobjr** [comment]
Hi, thank you for the report.

To be able to investigate the issue I'm going to need the information from the /debugpaste command, the seed of a world that the box appeared, and the coordinate that it has appeared.

**Comment by Jl1mbo** [comment]
> Hi, thank you for the report.
> 
> To be able to investigate the issue I'm going to need the information from the /debugpaste command, the seed of a world that the box appeared, and the coordinate that it has appeared.

https://hastebin.com/apevaluyok

**Comment by Jl1mbo** [comment]
575 5 -600

**Comment by joserobjr** [comment]
What is the seed of the world that generated the box? You can get from the /seed command

If the world is currently in use in a public server and you don't want to share it publicly, you can send it privately by discord (joserobjr#0001 - https://powernukkit.org/discord) or by e-mail: joserobjr@powernukkit.org

**Comment by joserobjr** [comment]
![image](https://user-images.githubusercontent.com/3679022/95097354-c36e1580-0703-11eb-8792-289486eec1c9.png)
