### ISSUE TITLE
Converting from Bedrock LevelDB worlds

### ISSUE THREAD

**Issue by recapitalverb** [PowerNukkit/PowerNukkit#694]
# 🤷‍♀️ I have a question

How should one convert LevelDB worlds to a format that PowerNukkit can understand? I have a `.mcworld` file exported from a Bedrock Realm, and I want to set up a PowerNukkit server using the same world files.

**Comment by recapitalverb** [comment]
https://hastebin.com/xubetesuzo

**Comment by joserobjr** [comment]
I don't know any lossless converter right now, but there are some lossy converters that converts mcworld to Java Edtion world, if you manage to convert to Java Edition 1.15.2 or lower than you can use Minecraft Java Edition itself to optimize the world to the full 1.15.2 format and than use https://github.com/PowerNukkit/Java2Nukkit-World-Converter#minecraft-java-to-nukkit-world-converter to convert 1.15.2 to the Cloudburst Nukkit format (with more losses), and than load the world in PowerNukkit.

As you can see, there are lots of steps, a lot of losses, and a lot of potential failures.

I created the Java2Nukkit World Converter and I do have plans to upgrade it to convert Java 1.16.x worlds directly to PowerNukkit.

I was doing a universal converter in the past but I can't find it anymore, sadly.
