### ISSUE TITLE
Burning arrow and rain will make a lot of particles

### ISSUE THREAD

**Issue by GoodLucky777** [PowerNukkit/PowerNukkit#700]
# 🐞 I found a bug

### 📸 Screenshots / Videos

![Screenshot](https://user-images.githubusercontent.com/43497313/95694344-93c38e00-0c6c-11eb-8716-e9c6fdfb15d2.png)

### ▶ Steps to Reproduce

1. Shoot a burning arrow.
2. If it is raining, it will make a lot of particles.

### ✔ Expected Behavior

If it is raining, fire will be extinguished.

### ❌ Actual Behavior

It is burning.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-SNAPSHOT (e2ea620bc9ef683a1365258fc933b1eba81e5469)
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

N.A

**Comment by LoboMetalurgico** [comment]
Fixed in #702
