### ISSUE TITLE
Campfire puts on the ground and comes back to hand in 1.4.0.0-PN

### ISSUE THREAD

**Issue by IrineuMC** [PowerNukkit/PowerNukkit#713]
# 🐞 I found a bug
**When you put a campfire on the ground, it goes back to your hand and stays on the ground buggy, like a duplicate**

### 📋 Debug information
* PowerNukkit version: 1.4.0.0-PN

**Comment by Htepple** [comment]
can't reproduce

**Comment by RORIdev** [comment]
Insufficient description, please use /debugpaste and post it here. It is impossible to determine which `1.4.0.0-PN` are you talking about.

**Comment by IrineuMC** [comment]
/debugpaste https://github.com/PowerNukkit/PowerNukkit/milestone/15

**Comment by XKazzuKX** [comment]
> /debugpaste https://github.com/PowerNukkit/PowerNukkit/milestone/15

You need to use the debugpaste command on your server and share the link it gives you

**Comment by IrineuMC** [comment]
Now this error has stopped, sorry for the unnecessary report
