### ISSUE TITLE
PlayerLoginEvent is called 2 times

### ISSUE THREAD

**Issue by Superzock3003** [PowerNukkit/PowerNukkit#720]
# 🐞 I found a bug

### 📸 Screenshots / Videos

![image](https://user-images.githubusercontent.com/67550519/97355725-968ec780-1897-11eb-81c3-293f614f1373.png)

### ▶ Steps to Reproduce

Join the server

### ✔ Expected Behavior
PlayerLoginEvent is called 1 time

### ❌ Actual Behavior
Sometimes PlayerLoginEvent is called 2 times

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT (2fa4687)
* Debug link: ✍
* Timings link (if relevant): ✍ 

### 💬 Anything else we should know?
 
I've found the bug because Luckperms sometimes kick the player.

**Comment by Superzock3003** [comment]
@RORIdev Why Plugin Issue? In the Screenshot above you can see that the player joins the server two times in the same second.

**Comment by RORIdev** [comment]
When testing *without* luckperms the issue doesn't occours, which lead us to believe it were a plugin issue. Your description of how you foind it also support this assumption. Therefore we decided to re-categorize this issue to `Type:Plugin Issue`.
