### ISSUE TITLE
Enchants?

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#724]
# 🐞 I found a bug
 First, i have a question. I have enchantet my sword with sharpness, and looting but it doesnt work by killing mobs.
Is this a bug by Nukkit or MobPlugin ?
I use MobPlugin 
PowerNukkit 1.3.1.5 PN Custom

### ▶ Steps to Reproduce

1. Enchant a Sword or axe with looting or sharpness
2. Kill Mobs 
3. Now you can see the looting enchant doesnt work

### 📋 Debug information

* PowerNukkit version: ✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by hteppl** [comment]
MobPlugin
