### ISSUE TITLE
Sponge doesn't work

### ISSUE THREAD

**Issue by Superzock3003** [PowerNukkit/PowerNukkit#726]
# 🐞 I found a bug

### 📸 Screenshots / Videos

https://youtu.be/gfSW5aNPmII

### ▶ Steps to Reproduce

1. Place a sponge into water

### ✔ Expected Behavior

1. The sponge would absorb the water.
2. The sponge would absorb the water from the waterlogged block

### ❌ Actual Behavior

1. nothing
2. The waterlogged block disapeares.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT (6458c38)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by good777LUCKY** [comment]
Duplicated with #94 and #643.
