### ISSUE TITLE
Enchanted Apple

### ISSUE THREAD

**Issue by Jl1mbo** [PowerNukkit/PowerNukkit#728]
# 🐞 I found a bug
If you eat an enchanted apple, the effect is not issued correctly

### 📸 Screenshots / Videos
![yvPzo-sOLnc.jpg](https://user-images.githubusercontent.com/51165317/97778628-69058f00-1bb3-11eb-95ca-35283fbb7c01.jpg)

### ✔ Expected Behavior
 Regeneration lvl 2

### ❌ Actual Behavior
 Regeneration lvl 5

### 📋 Debug information

* PowerNukkit version: ✍ 1.4.0.0

**Comment by good777LUCKY** [comment]
Regeneration lvl 5 is the correct effect in Bedrock Edition.
