### ISSUE TITLE
Players with spaces on the name cant craft items

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#732]
# 🐞 I found a bug
 Is this a Plugin they Block that?
Sorry for my questions i have changed from PM to PowerNukkit because its too good

### ▶ Steps to Reproduce

1. Have a namespace in youre name
2. Click on 'Crafting Table'
3. Crafting is Not possible

### 📋 Debug information

* PowerNukkit version: 
* Debug link: https://debugpaste.powernukkit.org/pastes/renehasisa
* Timings link (if relevant): ✍ 

### 💢 Crash Dump, Stack Trace and Other Files
 https://youtu.be/MIsVMFMvwwg

**Comment by MonoAdrian23** [comment]
At least, i have tried an SpaceRemover but isnt work

**Comment by MrRazamataz** [comment]
This works for me, didnt know that was an issue tho.
https://cloudburstmc.org/resources/nospaceinname.241/

**Comment by MrRazamataz** [comment]
But it looks like you already have that...

**Comment by MonoAdrian23** [comment]
I can delete it but it doesnt work. Only Players with namespace cant craft

**Comment by MrRazamataz** [comment]
Then dont delete it?

**Comment by MonoAdrian23** [comment]
I have test it without space remover and with space remover.
Players cant craft.
I have try to Change my Version to Nukkit and now it works

**Comment by MonoAdrian23** [comment]
https://youtu.be/MIsVMFMvwwg

**Comment by Gabriel8579** [comment]
It seems to be an issue with this plugin "BanItem v2.8", could you test without it?

**Comment by MonoAdrian23** [comment]
I have remove it but it still not work

**Comment by Gabriel8579** [comment]
Are any errors generated on the console?

**Comment by MonoAdrian23** [comment]
No errors

**Comment by MonoAdrian23** [comment]
Hey, i have found the Bug.
I must delete his Player Data but i cant because all Player datas are numeric.
Is there a Plugin for it to Show Player Data as name in Players folder?
