### ISSUE TITLE
Hoppers don't dispense into hoppers.

### ISSUE THREAD

**Issue by MrRazamataz** [PowerNukkit/PowerNukkit#741]
# 🐞 I found a bug

Hoppers don't dispense into hoppers.

### ✔ Expected Behavior
 They should. 

### ❌ Actual Behavior
 They dont.

### 📋 Debug information
1.4.0.0-PN-SNAPSHOT (git-93cac02)

**Comment by zombihunterbonn** [comment]
Hopper works fine at my actual blending version

powernukkit[bot] <notifications@github.com> schrieb am Mo., 9. Nov. 2020,
12:28:

**Comment by PocketMiner82** [comment]
Maybe you locked one of the hoppers (read the locked hopper bug in #750)

**Comment by MrRazamataz** [comment]
Ok.

**Comment by MrRazamataz** [comment]
I'm pretty sure the issue was they don't lock when they are meant to.
