### ISSUE TITLE
Boats are only oak when placed or broken. 

### ISSUE THREAD

**Issue by MrRazamataz** [PowerNukkit/PowerNukkit#745]
# 🐞 I found a bug
If you craft a boat that isn't made of oak, when you place it, it turns into an oak boat . When you break the boat it drops and oak boat.

### 📋 Debug information
* PowerNukkit version: ✍ 1.4.0.0-PN-SNAPSHOT (git-93cac02)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MrRazamataz** [comment]
1.4.0.0-PN-SNAPSHOT (git-93cac02)

**Comment by good777LUCKY** [comment]
I fixed in #708 but I don't know when it will be merged.

**Comment by MrRazamataz** [comment]
Ok thanks.
