### ISSUE TITLE
Redstone isn't vanilla.

### ISSUE THREAD

**Issue by MrRazamataz** [PowerNukkit/PowerNukkit#751]
# 🐞 I found a bug
Some of this has been quoted from my server players.

What doesn't work:
"Like droppers doesnt put items into another dropper that faces to its hole when activated"

"Anyways redstone is a big issue here.
Another problem with redstone as well, hoppers dont get locked when theres a redstone signal nearby. Bruh it breaks alot of my farms and machines.But torch can lock it somehow."

If there are more issues I'll comment or edit this message. Or create a new issue.

**Comment by PocketMiner82** [comment]
I'm working on it in #750, but it could take some time.

**Comment by MrRazamataz** [comment]
Ok cool. Here is some more 
"Pistons sometimes enter a glitched state where they show as retracted but the hitbox shows that it is extended. Also sticky pistons lose their sticky sometimes"

"Minecarts dont loop when they supposed to."

**Comment by PocketMiner82** [comment]
> Ok cool. Here is some more
> "Pistons sometimes enter a glitched state where they show as retracted but the hitbox shows that it is extended. Also sticky pistons lose their sticky sometimes"
> 
> "Minecarts dont loop when they supposed to."

The first one is fixed with the block entity updates, but I don't understand the second one, wdym with "loop"?

**Comment by MrRazamataz** [comment]
> > Ok cool. Here is some more
> > "Pistons sometimes enter a glitched state where they show as retracted but the hitbox shows that it is extended. Also sticky pistons lose their sticky sometimes"
> > 
> > "Minecarts dont loop when they supposed to."
> 
> The first one is fixed with the block entity updates, but I don't understand the second one, wdym with "loop"?

They dont rebound when they are in falling state but stuck to the block

**Comment by MrRazamataz** [comment]
It should be:
https://cdn.discordapp.com/attachments/727098758613172274/776435899768111114/2020_11_12_21_06_52.mp4

What is does:
https://cdn.discordapp.com/attachments/727098758613172274/776436052175880202/2020_11_12_21_17_24.mp4

**Comment by PocketMiner82** [comment]
I'm getting access denied, when trying to open your link. Could you directly upload it to github (zip the videos) or send youtube link? @MrRazamataz

**Comment by MrRazamataz** [comment]
I'm gonna try and get them back. Sorry there were deleted.

**Comment by PocketMiner82** [comment]
@MrRazamataz have you found them? I think GitHub also allows direct video uploading now, so you can send it here
