### ISSUE TITLE
Bed Missing Behavior

### ISSUE THREAD

**Issue by LostAraneus** [PowerNukkit/PowerNukkit#760]
# ❇ Feature Request

### ✔ Expected Behavior
When you click the bed at day it should set respawn point
### ❌ Actual Behavior
When you click the bed at day it doesn't save the respawn and you have to wait for night to come then set respawn

### 💬 Anything else we should know?
If this was already a bug that has been submitted before let me know and ill delete this 😊

**Comment by good777LUCKY** [comment]
Duplicated with #620

**Comment by LostAraneus** [comment]
Alright
