### ISSUE TITLE
Bookshelf bug/glitch

### ISSUE THREAD

**Issue by LostAraneus** [PowerNukkit/PowerNukkit#762]
# 🐞 I found a bug

### 📸 Screenshots / Videos
None

### ▶ Steps to Reproduce
1. Craft a bookshelf

### ✔ Expected Behavior
For the bookshelf to be crafted 

### ❌ Actual Behavior
It doesnt crafts it and returns all the bookd and blocks u used
Also if you placed it on creative it turns the block to a repeating command block? Idk why

### 📋 Debug information
* PowerNukkit version: PowerNukkit v1.3.1.5-PN 
* Debug link: ✍
* Timings link (if relevant): ✍ 

### 💢 Crash Dump, Stack Trace and Other Files
None

### 💬 Anything else we should know?
😊

**Comment by MrRazamataz** [comment]
Delete the vanilla command block plugin or update to bleeding branch as this fixes this issue with the plugin.

**Comment by LostAraneus** [comment]
Thanks i just had to remove the plugin and it works
