### ISSUE TITLE
Issue with cache chunks setting in nukkit.yml

### ISSUE THREAD

**Issue by MrRazamataz** [PowerNukkit/PowerNukkit#790]
It seems that when `cache-chunks: false` chunks load fine and its all good and players can join but when `cache-chunks: true` people are reporting chunks don't load and errors in console.
With cache-chunks: true
(not my screenshot)
![image](https://user-images.githubusercontent.com/56600481/100265291-f6849680-2f47-11eb-870f-817cddb28281.png)

With it false it seems to be ok.
If more thing are found, I will update this post.

**Comment by MrRazamataz** [comment]
Seems to be a new issue with client, issue is happening on both 1.3.x.x and 1.4 snapshot.

**Comment by MonoAdrian23** [comment]
This is a Minecraft Issue.

**Comment by RealTriassic** [comment]
I'm getting this too

**Comment by RealTriassic** [comment]
and i have cache-chunks disabled, so it's clearly nothing to do with caching chunks.

**Comment by MrRazamataz** [comment]
Oh. Nvm then.
