### ISSUE TITLE
NPC skins are show as a steve skin

### ISSUE THREAD

**Issue by Superzock3003** [PowerNukkit/PowerNukkit#796]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Place a NPC

### ✔ Expected Behavior

NPC skins are shown as player skin

### ❌ Actual Behavior

NPC skins are shown as steve skin

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-ALPHA.2-SNAPSHOT (git-83ecf74)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MrClean1337** [comment]
This will fix https://github.com/CloudburstMC/Nukkit/commit/fa4a414cdb1c4e98a168557bb0812c9125937cfd

Tested by me!

**Comment by Superzock3003** [comment]
Fixed (https://github.com/PowerNukkit/PowerNukkit/pull/831)
