### ISSUE TITLE
Some players can't earn xp

### ISSUE THREAD

**Issue by MrRazamataz** [PowerNukkit/PowerNukkit#799]
# 🐞 I found a bug
Some players can't earn xp. Not many players have said about it so I feel that it's not a problem for everyone. When I pick up xp orbs, my xp bar doesn't go up. I think that mending tools get repaired but xp bar doesn't increase.

### ✔ Expected Behavior
https://minecraft.gamepedia.com/Experience

### ❌ Actual Behavior
XP doesnt increase.

### 📋 Debug information
1.4.0.0 SNAPSHOT (bleeding branch)
Server running git-83ecf74 at this very moment, I'm gonna update it to 1f343fc soon.

Video: 
https://www.youtube.com/watch?v=FrWvO4xakO4

**Comment by MrRazamataz** [comment]
Video:
https://www.youtube.com/watch?v=FrWvO4xakO4

**Comment by LoboMetalurgico** [comment]
Is this bug still occurring?

**Comment by MrRazamataz** [comment]
Probably.

**Comment by LoboMetalurgico** [comment]
Would it be possible to confirm? I can't replicate it here.

**Comment by MrRazamataz** [comment]
I do not use PowerNukkit anymore so I cannot confirm this with testing, sorry.

**Comment by LoboMetalurgico** [comment]
No problems. In that case, unfortunately I will have to close this Issue since I couldn't replicate the situation.
If you or someone else can replicate and provide more details, I'll be happy to reopen this issue.

**Comment by MonoAdrian23** [comment]
I have tested it.

But its normal, XP, if a Mending Tool is in Inventory get all XP.
But this happens in Vanilla too.

All workes great.
