### ISSUE TITLE
Loom doenst work

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#807]
# 🐞 I found a bug
 

### ▶ Steps to Reproduce

1. Place a Loom
2. Click on Loom
3. There is no Interface for it

### 📋 Debug information

* PowerNukkit version: 1.4.0.0 Alpha 2
* Debug link: https://debugpaste.powernukkit.org/pastes/jacumoyera
* Timings link (if relevant): ✍

**Comment by MrRazamataz** [comment]
Duplicate of #422
