### ISSUE TITLE
I can't use grindstone

### ISSUE THREAD

**Issue by SS-YG** [PowerNukkit/PowerNukkit#816]
grindstone 
![image](https://user-images.githubusercontent.com/69110760/101620423-7d109c00-3a4f-11eb-882e-968162429bcf.png)

https://debugpaste.powernukkit.org/pastes/ekocujiniy

You can only put items in, but when you try to take them out, they will disappear. After closing the GUI, the items will return as they are.

**Comment by Gabriel8579** [comment]
Fixed at #1064. Closing
