### ISSUE TITLE
Dispeners won't fire into other dispensers (they do this in vanilla)


### ISSUE THREAD

**Issue by MrRazamataz** [PowerNukkit/PowerNukkit#820]
# 🐞 I found a bug
They will just fire it into the block so it ends up next to it

### ✔ Expected Behavior
They should fire into other dispensers.

### ❌ Actual Behavior

They will just fire it into the block so it ends up next to it.

### 📋 Debug information
(git-475659c)

**Comment by DesertSoldier43** [comment]
> # 🐞 I found a bug
> They will just fire it into the block so it ends up next to it
> 
> ### ✔ Expected Behavior
> They should fire into other dispensers.
> 
> ### ❌ Actual Behavior
> They will just fire it into the block so it ends up next to it.
> 
> ### 📋 Debug information
> (git-475659c)

You need to use droppers to fire it in the other, dispensers don't dispense items into other blocks with inventories, only droppers can do it.

**Comment by PocketMiner82** [comment]
this behavior is implemented in #750 (for droppers, as dispensers don't do it)

**Comment by MrRazamataz** [comment]
Sorry, it was a player who told me this and I didnt really understand but it seemed to be a bug so I reported it in their words, I will let them know this.
