### ISSUE TITLE
I can't use the 'command block'

### ISSUE THREAD

**Issue by tr46rsm** [PowerNukkit/PowerNukkit#823]
![Ekran Görüntüsü (6)](https://user-images.githubusercontent.com/75860811/101951779-99a40400-3c08-11eb-97f8-246b4da72621.png)

![Ekran Görüntüsü (5)](https://user-images.githubusercontent.com/75860811/101951745-8f820580-3c08-11eb-868a-98d204d591d7.png)

I can't use the 'command block'

**Comment by tr46rsm** [comment]
https://hastebin.com/ilujijemey

**Comment by tr46rsm** [comment]
I can't use the 'command block'

**Comment by MonoAdrian23** [comment]
Can anyone close this Issue Please?
Its duplicate of #828
Problem solved

**Comment by RORIdev** [comment]
CommandBlock isn't implemented by PN yet. Also Duplicate of #828

**Comment by tr46rsm** [comment]
✓

3 Oca 2021 Paz 18:18 tarihinde RORIdev <notifications@github.com> şunu
yazdı:
