### ISSUE TITLE
Error whilst processing the packet 8:ResourcePackClientResponsePacket

### ISSUE THREAD

**Issue by andrei1058** [PowerNukkit/PowerNukkit#827]
# 🐞 I found a bug

I just installed PowerNukkit on my PC and when I tried to join there was that packet conversion issue I guess. I think it needs to be updated or something. I'm not using a resourcepack. After the error it didn't let me in and when I clicked "Cancel" to disconnect, mc client was stuck. After restarting the server the error no longer appeared.

### ▶ Steps to Reproduce

1. Install a new server
2. Join with latest win 10 version

### 📋 Debug information

* PowerNukkit version: ✍1.4.0.0-PN-ALPHA.1 (git-91f3b12) "PowerNukkit" (API 1.0.11)
* Debug link: ✍
* Timings link (if relevant): ✍ 

### 💢 Crash Dump, Stack Trace and Other Files

https://pastebin.com/eEB3A8TS

**Comment by MonoAdrian23** [comment]
Use the latest Snapshot Version of PowerNukkit.
Its fixed.
