### ISSUE TITLE
I can't use the 'command block'

### ISSUE THREAD

**Issue by tr46rsm** [PowerNukkit/PowerNukkit#828]
![Ekran Görüntüsü (6)](https://user-images.githubusercontent.com/75860811/101951779-99a40400-3c08-11eb-97f8-246b4da72621.png)

![Ekran Görüntüsü (5)](https://user-images.githubusercontent.com/75860811/101951745-8f820580-3c08-11eb-868a-98d204d591d7.png)

I can't use the 'command block'

https://debugpaste.powernukkit.org/pastes/ilujijemey

**Comment by MonoAdrian23** [comment]
Use a Plugin for it.
https://github.com/wode490390/VanillaCommandBlock

**Comment by tr46rsm** [comment]
Thank you
