### ISSUE TITLE
Cant rename with Anvil

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#829]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Place a Anvil
2. Click on 'Anvil'
3. Put all needed Items for Rename in Anvil and choose a name of youre wish.
4. Now you can see, name is the same

### 📋 Debug information

* PowerNukkit version: 1.4.0.0 Alpha 2
* Debug link: https://debugpaste.powernukkit.org/pastes/axikedonul
* Timings link (if relevant): ✍

**Comment by RealTriassic** [comment]
Can confirm, happens to me too ^
![image](https://user-images.githubusercontent.com/40073455/102018898-ddb61680-3d78-11eb-9f29-265fb6d213d1.png)

**Comment by MrRazamataz** [comment]
Same, players are reporting it.

**Comment by Camotoy** [comment]
This should be addressed with https://github.com/CloudburstMC/Nukkit/pull/1734.

**Comment by LoboMetalurgico** [comment]
@Camotoy could you port this PR to the PowerNukkit? Merges from Cloudburst require a lot more time and attention before being merged here.
