### ISSUE TITLE
Critical problem by switching between powernukkit servers

### ISSUE THREAD

**Issue by MrClean1337** [PowerNukkit/PowerNukkit#837]
# 🔌 Critical problem by switching between powernukkit servers
If you use the latest waterdog https://github.com/WaterdogPE/Waterdog/tree/master-zlib
and the latest PN https://github.com/PowerNukkit/PowerNukkit/tree/bleeding
(Its even in bleeding-1.3 if you change the version strings)

you'll have sometimes problems if you switch between servers.

Raknet wouldn't really close the connection if a player goes offline (switches to another server)
So the client stands still on the source server and is in the same time connected with the target server.
So the client will get/send packets from both servers at the same time.

Some user told me that this is fixed for him since this commit on cloudburst https://github.com/CloudburstMC/Nukkit/commit/cd20c264e9f6231dfd716d5b803fbf2d56ea1f38
But im using powernukkit

### 📸 Screenshots / Videos
[Here a full detailed workaround](https://youtu.be/pmtoHTFdcXw)

### ▶ Steps to Reproduce
1. Join
2. Connect to a server
3. switch to another server and you'll get that bug

### ✔ Expected Behavior
Switching servers without problems ? :D

### ❌ Actual Behavior
Client stays connected on the source server and is in the same time connected with the target server

### 📋 Debug information
* PowerNukkit version: 1.3.2.0-PN-ALPHA.3-SNAPSHOT (Already tested with "bleeding", same result)
* Debug link: https://debugpaste.powernukkit.org/pastes/yequmopaxu

### 💬 Anything else we should know?
Its critical

**Comment by Gabriel8579** [comment]
Hi, sorry for the delay in solving your problem, but probably PR #1033 should have solved it, could you try it out?

**Comment by MrClean1337** [comment]
Its so old, you can close it. Fixed.

**Comment by Gabriel8579** [comment]
Thank you, closing as stale
