### ISSUE TITLE
You cant eat spider eyes.

### ISSUE THREAD

**Issue by MrRazamataz** [PowerNukkit/PowerNukkit#851]
# 🐞 I found a bug
You cant eat spider eyes.
### 📸 Screenshots / Videos
https://www.youtube.com/watch?v=K1p2pAM9j8M

https://minecraft.gamepedia.com/Spider_Eye

### 📋 Debug information
git-bb4dff3 (its not fixed yet in newer versions, updating soon to them tho)

**Comment by alikindsys** [comment]
Tracking moved to #1366
