### ISSUE TITLE
Outdated Server on Minecraft version 1.16.200

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [PowerNukkit/PowerNukkit#852]

**Comment by MonoAdrian23** [comment]
Please use the latest Bleeding 
https://github.com/PowerNukkit/PowerNukkit/suites/1700312680/artifacts/31996735

Or try Version Extension Plugin from Cloudburst.

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
I still encounter the issue using the latest bleeding edge version. Could you provide a link to the plugin you mentioned? Thanks.

**Comment by LostAraneus** [comment]
This is the link of the version extension:
https://cloudburstmc.org/resources/versionextension.521/
Just add 422 as protocol in config

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
In the "config.yml" file, correct? Even still, I can't connect but receive a different error. 
PLAYER[/12.34.56.78:000000] logged out due to Disconnected from Server

**Comment by LoboMetalurgico** [comment]
Try use this version https://github.com/PowerNukkit/PowerNukkit/suites/1710894103/artifacts/32284871

**Comment by LoboMetalurgico** [comment]
Closing as fixed
