### ISSUE TITLE
Server Crash/Inventory Transaction

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#866]
# 🐞 I found a bug
 https://debugpaste.powernukkit.org/pastes/ibiqukuqod.http

### ▶ Steps to Reproduce

1. Please read my Hastebin

### 📋 Debug information

* PowerNukkit version: 1.4.0.0 Alpha 2
* Debug link: https://debugpaste.powernukkit.org/pastes/usivegaras
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
This Player have's only Break Stone with a Diamond pickaxe

**Comment by RealTriassic** [comment]
this is useless, provide more information.

**Comment by MonoAdrian23** [comment]
There isn't more information.

**Comment by MonoAdrian23** [comment]
I think you forgot to read my First Hastebin Link in Bug description.
There is the complete Error
