### ISSUE TITLE
Snow logging

### ISSUE THREAD

**Issue by PocketMiner82** [PowerNukkit/PowerNukkit#876]
# ❇ Feature Request
Snow logging is not implemented.

### ✔ Expected Behavior
Place snow layer on e.g. grass, the snow should be there and the grass too.

### ❌ Actual Behavior
It works only client side; but if you rejoin, there is only the snow layer left, so the server doesn't know it's snow logged.

### Debug:
1.4; https://github.com/PowerNukkit/PowerNukkit/commit/b00df764562a3f8a04b2a09c551912417b1a5691

**Comment by PocketMiner82** [comment]
1.4; https://github.com/PowerNukkit/PowerNukkit/commit/b00df764562a3f8a04b2a09c551912417b1a5691

**Comment by GoodLucky777** [comment]
Duplicate of #611
