### ISSUE TITLE
Chests filled with seeds cause the player to enter an infinite loading screen

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#891]
# 🐞 I found a bug
 We have a Problem, when a Player open a DoubleChest, he can do nothing because a Endless Loading Screen appears.
Open the Chat doenst Work.
Do another things doesnt work.
He must rejoin for it, but when this Player try this, he cant Connect to the Server.
It doenst happen with all chests!

### ▶ Steps to Reproduce

1. Place a DoubleChest
2. Fill it complete
3. Much Players cant Open the Chest Inventory because a Endless Loading Screen appears
4. But i can reproduce this, because it doenst Happens with all chests.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0 Latest Bleeding
* Debug link: https://debugpaste.powernukkit.org/pastes/utuyiqegic
* Timings link (if relevant): ✍

**Comment by RealTriassic** [comment]
I've had this too.

**Comment by hteppl** [comment]
same

**Comment by LoboMetalurgico** [comment]
Are the chests in which this happens in different chunks?

**Comment by MonoAdrian23** [comment]
No

**Comment by MonoAdrian23** [comment]
I have tried to Break the DoubleChest and Same Problem. (Endless Loading Screen)
But after rejoin, i can Open the singlechest.
I have tested it in my Plotworld.

**Comment by RORIdev** [comment]
The chest is filled with normal stackable items or something unusual?

**Comment by MonoAdrian23** [comment]
Only Seeds in Stacks, Beetroot, Wheat, Potato, Carrots

**Comment by RORIdev** [comment]
> Only Seeds in Stacks, Beetroot, Wheat, Potato, Carrots

Wierd, but this'll help us thanks for the info.

**Comment by RORIdev** [comment]
Why are these issues getting closed? Did they got fixed on a newer version? Please specify the reason behind the closure.

**Comment by MonoAdrian23** [comment]
I have closed this Issue, because this problem doenst exist no longer for me.
I have test it with single and doublechests and all works great.

**Comment by RORIdev** [comment]
Aight, then thats good. This constant issue closing thing got us a bit worried. Good to know this was the reason. I'll assume this is the same reason for all the others.
