### ISSUE TITLE
Players cant Join after Server quit

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#906]
# 🐞 I found a bug
 2021-01-11 13:57:25.452 [Network Listener - #10] ERROR - An exception occurred in RakNet (Server)
io.netty.channel.unix.Errors$NativeIoException: sendToAddress(..) failed: Operation not permitted

### ▶ Steps to Reproduce

1. Sorry but i dont know why this Happens
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-3bb9763)
* Debug link:  /debugpaste doesnt work at this moment
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
I have closed this because I think it was solved
But in commit (git-3bb9763) now it happens again.

**Comment by Gabriel8579** [comment]
I will close this issue as a duplicate to continue the discussion in #1056 as it already has some possible solutions. Thanks
