### ISSUE TITLE
Players don't get kicked when the server stops

### ISSUE THREAD

**Issue by Superzock3003** [PowerNukkit/PowerNukkit#912]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Join the server
2. stop server

### ✔ Expected Behavior
Players get kicked

### ❌ Actual Behavior
Players time out after a few seconds

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT (git-5da77fe)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by Gabriel8579** [comment]
Fixed at #1033. Closing
