### ISSUE TITLE
SPONGES

### ISSUE THREAD

**Issue by RizenSoulja** [PowerNukkit/PowerNukkit#913]
# ❇ Feature Request

### ✔ Expected Behavior
 
1.) Place a dry sponge in water
2.) Sponge turns into a wet sponge
3.) Removes all water within a 7x7 Cube radius (REF: https://minecraft.gamepedia.com/Sponge ) 

### ❌ Actual Behavior

1.) Place dry sponge in water
2.) Sponge turns into a wet sponge but does not remove any water around it

### 💬 Anything else we should know?

Thanks in advanced

**Comment by GoodLucky777** [comment]
It is duplicated with #94
