### ISSUE TITLE
Players can't join server

### ISSUE THREAD

**Issue by Superzock3003** [PowerNukkit/PowerNukkit#919]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Join Server

### ✔ Expected Behavior
Players can join the server

### ❌ Actual Behavior
Players are in an infinite loading screen

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT (git-bff2431)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by Jl1mbo** [comment]
Can you provide a debugpaste link?

**Comment by Jl1mbo** [comment]
Yes, you're right, the entrance doesn't work.

**Comment by ALIENN43** [comment]
i also face the problem ！

**Comment by Superzock3003** [comment]
Fixed

**Comment by hackerstudios** [comment]
it isnt fixed
