### ISSUE TITLE
Redstone repeater extend bug.

### ISSUE THREAD

**Issue by Phongsiri33013Winsan2020TH** [PowerNukkit/PowerNukkit#927]
# 🐞 I found a bug

### 📸 Screenshots / Videos

https://www.youtube.com/watch?v=eVv1pdPW3-o

### ▶ Steps to Reproduce

1. Place redstone repeater.
2. Extend it.
3. Activate it using button, etc.
4. It working like repeater that did not extend.

### ✔ Expected Behavior

It will send a redstone signal slower if extend it.

### ❌ Actual Behavior

Extend it to any type. It still send same redstone signal.

### 📋 Debug information

* PowerNukkit version: ✍ 1.4.0.0-PN-ALPHA.2
* Debug link: ✍ Its not my server sorry.
* Timings link (if relevant): ✍ Its not my server sorry.

### 💢 Crash Dump, Stack Trace and Other Files

Its not my server sorry.

### 💬 Anything else we should know?

Its not my server sorry.

**Comment by Phongsiri33013Winsan2020TH** [comment]
Nukkit 1.4.0.0-PN-ALPHA.2 (git-24bd183) PowerNukkit API Version 1.0.11 MCBE 1.16.200 Protocol 422

At least I can /about without permission.

**Comment by PocketMiner82** [comment]
You need to update to the latest bleeding branch, it contains lots of redstone fixes (#750)

**Comment by RORIdev** [comment]
24bd183 is around a month old by now, since 1127d0c we've added a lot of redstone related fixes. Can you please test that again on a newer bleeding release?

**Comment by Phongsiri33013Winsan2020TH** [comment]
ok sry i don't know this thing. it not my server
