### ISSUE TITLE
Brewing stand doesn't work properly

### ISSUE THREAD

**Issue by SS-YG** [PowerNukkit/PowerNukkit#928]
![image](https://user-images.githubusercontent.com/69110760/105031294-150e9600-5a90-11eb-9996-1671fcace94a.png)
Brewing stand doesn't work properly
![image](https://user-images.githubusercontent.com/69110760/105031370-340d2800-5a90-11eb-9d77-013aa6e2c6e0.png)
https://debugpaste.powernukkit.org/pastes/akaqibomik

**Comment by Jl1mbo** [comment]
yes
