### ISSUE TITLE
Flying boats

### ISSUE THREAD

**Issue by AVxSpacelime** [PowerNukkit/PowerNukkit#936]
Listen im not a server owner or a developer or anything its just this stuff is getting very annoying

Flying boats fix them plz. Came here from stupid craft where ppl are losing kits to kids running into warp pvp and trapping ppl in flying boat glitches where they cant get out of, wether it be by trying to tp or by exiting the boat. Sbd when they relog it spawns em in the void and kills em.

**Comment by joserobjr** [comment]
Thank you for the report! This issue is already reported but your extra evidence and data provided may help to solve the issue.

Closing as duplicated, let's keep this thread at #853
