### ISSUE TITLE
Players can't turn campfires on by walking over them

### ISSUE THREAD

**Issue by Superzock3003** [PowerNukkit/PowerNukkit#944]
# 🐞 I found a bug

### 📸 Screenshots / Videos

Vanilla: https://youtu.be/8FDoSxCcUiw
PowerNukkit: https://youtu.be/Yf1YutKndRo

### ▶ Steps to Reproduce

1. Place a campfire
2. burn yourself
3. walk over the campfire

### ✔ Expected Behavior
The campfire will turn on

### ❌ Actual Behavior
nothing happenes

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT (cade5f5)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by GoodLucky777** [comment]
I added it in pull request #783 (awaiting review)
