### ISSUE TITLE
getConfig error

### ISSUE THREAD

**Issue by huz17-1337** [PowerNukkit/PowerNukkit#951]
When you run getConfig().getStringList("Key") you get 
`java.lang.ClassCastException: cn.nukkit.utils.ConfigSection cannot be cast to java.util.List`

in version `1.4.0.0-PN-ALPHA.2 (git-24bd183) "PowerNukkit" (API: 1.0.11)`

**Comment by Jl1mbo** [comment]
This error occurs if you try to get a non-List

**Comment by Jl1mbo** [comment]
Show how you write values

**Comment by huz17-1337** [comment]
My config looks like this:
config.yml
`User:
  695b613d-3d7c-3f58-bf4b-7e9236abec9a: {"test.pl.perm","another.perm"}`
my code to get it looks like this:
`this.getServer().getLogger().info(getConfig().getStringList("User").get(0).toString());`

**Comment by huz17-1337** [comment]
well and after it error the config looks like this 

User:
  695b613d-3d7c-3f58-bf4b-7e9236abec9a:
  - test.pl.perm
  - another.perm

**Comment by Jl1mbo** [comment]
It is not a sheet, to check if it is a sheet use config.isList("key");

**Comment by huz17-1337** [comment]
nvm i fixed it
