### ISSUE TITLE
Weird Slab

### ISSUE THREAD

**Issue by GoodLucky777** [PowerNukkit/PowerNukkit#977]
# 🐞 I found a bug

### 📸 Screenshots / Videos

![Screenshot](https://user-images.githubusercontent.com/43497313/108171309-b0059900-713e-11eb-9983-238194bb1e65.jpg)

### ▶ Steps to Reproduce

Unknown

### ✔ Expected Behavior

Slab should not be like that.

### ❌ Actual Behavior

Slab can be like that.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT (54cbf48d7d94c188e9270164d4c1ba0a16865043)
* Debug link: -
* Timings link (if relevant): - 

### 💢 Crash Dump, Stack Trace and Other Files

Unknown

### 💬 Anything else we should know?

-

**Comment by alikindsys** [comment]
Moved the tracking to #1318.
