### ISSUE TITLE
Dying from Magma Block causes a broken player death message to appear.

### ISSUE THREAD

**Issue by RealTriassic** [PowerNukkit/PowerNukkit#981]
# 🐞 I found a bug

### 📸 Screenshots / Videos

![image](https://user-images.githubusercontent.com/40073455/108621346-e1ca7880-743a-11eb-8e97-08e63e3057ba.png)

### ▶ Steps to Reproduce

1. Place a Magma Block
2. Go into Survival Mode
3. Step on it until you die.
4. Observe the broken "death.attack.lava.magma" death message being sent in chat.

### ✔ Expected Behavior

I expect the normal death message to appear.

### ❌ Actual Behavior

A broken one appears instead.

### 📋 Debug information

* PowerNukkit version: git-d96ebe4 PowerNukkit 1.4.0.0
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by joserobjr** [comment]
Thank you for reporting
