### ISSUE TITLE
Chunkload is very slow!

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#984]
# 🐞 I found a bug
 Chunkload is very slow since 1.16.200
I use Version 1.16.201 but the chunks loads only when placing or breaking a block in unloaded chunks.
I have test it without plugins.
And yes, it happens with all Bleeding Versions compatible with 1.16.200 or higher.

### ▶ Steps to Reproduce

1. Create a world
2. Teleport to world
3. Fly around the world 
4. See very slow chunk loading
5. Click a chunk for loading
6. Nukkit have's the Same Problem

### 📋 Debug information

* PowerNukkit version: 1.4.0.0 Alpha 2
* Debug link: (git-d96ebe4)
* Timings link :

**Comment by hteppl** [comment]
maybe client issue?

**Comment by hteppl** [comment]
https://minecraft.gamepedia.com/Bedrock_Edition_1.16.200
https://minecraft.gamepedia.com/RenderDragon

**Comment by MonoAdrian23** [comment]
No Client issue
Its fixed in 201
I use 201
In Pocketmine it works Well.
Only Nukkit and Powernukkit have's this

**Comment by Jl1mbo** [comment]
I use the latest version in Bleeding - everything loads quickly

**Comment by hteppl** [comment]
> I use the latest version in Bleeding - everything loads quickly

+

**Comment by MonoAdrian23** [comment]
Hm, can you send me a Link to latest Bleeding?

**Comment by joserobjr** [comment]
Hi, here is the direct link to the last successful 1.4.0.0-PN-SNAPSHOT build:
https://builds.powernukkit.org/repository/download/PowerNukkit_14/.lastSuccessful/powernukkit-1.4.0.0-PN-SNAPSHOT-shaded.jar

You can browse the builds, check their details and download other artifacts at https://builds.powernukkit.org , the jars are at the artifacts tab inside the builds
