### ISSUE TITLE
Crafting Recipe Book

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#999]
# 🐞 I found a bug
 You can't use the Crafting Recipe Book Examples for Crafting Tools and another Stuff.

### ▶ Steps to Reproduce

1. Place a Crafting Table
2. Try to craft with Recipe Book for example, Diamond Pickaxe
3. The Recipe isnt shown for craft, only diamonds 
4. I didn't know how much recipes not working

### 📋 Debug information

* PowerNukkit version: (git-1d52f45)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
![Screenshot_20210318-185918_Minecraft.jpg](https://user-images.githubusercontent.com/59027482/111682346-89617d80-8824-11eb-87c0-6093d07fa8fc.jpg)

**Comment by GoodLucky777** [comment]
i dont know why but it was not sending some tools in CreativeContentPacket
